### ISSUE TITLE
Strange behaviour of List viewer with Live Companion 

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#737] opened 2020-11-12 21:50 UTC
### Platform
✕ Android companion version 24101 

### Actual Behavior
List viewer shows only the first 10 items of a list of 100

The same list is ok with ✕ Android companion version 23702

**Comment by josmas** [comment] 2020-11-12 22:50
Hi @Bellacopia is your list embedded within other components? I cannot see it in an app with just a list viewer.

**Comment by josmas** [comment] 2020-11-12 23:05
Can you see it on this project? It has 12 elements and you scroll the list: https://x.thunkable.com/projectPage/5fadbe8db026690011fcdd10

**Comment by Bellacopia** [comment] 2020-11-12 23:06
No, my list is not embedded.  
Even the "Item click" block does not work.: in some cases it has no effect, while in others it crashes the app.
Anyway, there's something wrong with version 24101.

**Comment by Bellacopia** [comment] 2020-11-12 23:21
Here are two screenshots from the same list taken on two different devices: the first uses version 24101, the second version 23702:

![Lista 1](https://user-images.githubusercontent.com/63849566/99007872-5d1bb480-2545-11eb-9e06-004985a27e11.jpg)
![Lista 2](https://user-images.githubusercontent.com/63849566/99007875-5db44b00-2545-11eb-9714-ab6bf485fe7f.jpg)

**Comment by josmas** [comment] 2020-11-12 23:35
I have added clicks to the project above, can you please test it?

I can see the differences in the screenshots, but it might be an interaction with something else in there. Can you describe the layout of your screen? is it a row at the top (with a label and a button) and then the list just under it? do you have a fixed size for any of the components?

**Comment by Bellacopia** [comment] 2020-11-12 23:41
Correct! The list has standard parameters. But please note that I haven't changed anything on this screen in weeks.

**Comment by Bellacopia** [comment] 2020-11-12 23:49
I have now tried to open the backups of the previous versions of the app (fully functional) and now they give the same problem.

**Comment by josmas** [comment] 2020-11-13 00:04
I cannot reproduce on my side; can you please share a link to your project? Feel free to send it through Intercom if it is a private project.

**Comment by Bellacopia** [comment] 2020-11-13 00:32
ok but now intercom is not available... I'll try again tomorrow . Thank you

**Comment by Bellacopia** [comment] 2020-11-13 09:37
Please, may you confirm that Intercom is not yet available? Or is my browser having problems? Thank you

**Comment by josmas** [comment] 2020-11-13 13:33
hi there, it should always be available. Are you using any ad blockers or similar?

**Comment by Bellacopia** [comment] 2020-11-13 13:43
On my PC Google Chrome doesn't show Intercom. Now I have switched to MS Edge and I see it. I'll send you the link to my project and the instructions. See you there.

**Comment by Bellacopia** [comment] 2020-11-17 11:39
Hi Josmas,
Last Friday I sent you my project link with the instructions to reproduce the malfunctions, but I have not received any response. I am stuck and can't work on my project because of a stupid list that crashes. Please can you check Intercom and look at my project. Thanks

**Comment by josmas** [comment] 2020-11-17 13:18
Hi @Bellacopia I could not find your intercom message. Are you using a different user?

**Comment by Bellacopia** [comment] 2020-11-17 13:27
No, the account is the same. I'll send you again. Done

**Comment by Bellacopia** [comment] 2020-11-17 13:31
Do you find it?

**Comment by Bellacopia** [comment] 2020-11-17 13:32
Now Goutham in online

**Comment by josmas** [comment] 2020-11-17 14:03
Thanks @Bellacopia I've just sent him a message to assign your query to me.

**Comment by jane-d-alt** [comment] 2021-05-14 07:22
Hi there,
It looks like this behavior was resolved after being followed up on Intercom. To test if this behavior persists I created this [demo project](https://x.thunkable.com/projectPage/609e243b15d46a0012a53996/) which displays 20 items in a list viewer. I can see all of the items when I test on a device. I'll close this issue for now. Please reach out if you experience this behavior going forward.

**Closed by jane-d-alt** 2021-05-14 07:22 UTC
