### ISSUE TITLE
QR code reader in Thunkable X

### ISSUE THREAD

**Issue by aniolpages** [thunkable/thunkable-issues#189] opened 2019-07-15 17:49 UTC
I don’t know if anyone has requested the implementation of a QR code reader in Thunkable X, but I haven’t find it.
I used a lot the QR code reader in Thunkable Classic and now I need to use it again, but I like to use Thunkable X. I found an article showing the use of Cloudinary and a Web API, but this is not a good solution for me, because in most cases, there will not be internet connection in the phone or the necessary immediately of the scan (it’s a game that counts the time) it makes it impractical.

Thanks for considering the feature request and thanks for the great platform, docs and all the community!!

**Comment by mark-friedman** [comment] 2019-07-15 19:28
Duplicate of #35

**Closed by mark-friedman** 2019-07-15 19:28 UTC
