### ISSUE TITLE
Publish to web app does not show the latest update made.

### ISSUE THREAD

**Issue by StefanSladdenEng** [thunkable/thunkable-issues#692] opened 2020-10-08 12:22 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. I made several updates to the size of buttons on screen. Including changed from PX to % in sizes 
2. When looking in Live Preview i can see changes 
3. But When publish to Web App i cannot get the updates there. 
The URL just show the same app and display of it - as it was before started to change things   

### Project Link
https://thunkable.site/web-build/index.html?webAppId=EdabfVM6 

### Expected Behavior
Updates made to the app should vi visible / displayed in webb App

### Actual Behavior
Screen remains the same as before
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/60143626/95457680-84dd9280-0971-11eb-8b7a-297ab6459189.png)

**Comment by josmas** [comment] 2020-10-08 13:43
Duplicate of #691

**Closed by josmas** 2020-10-08 13:43 UTC
