### ISSUE TITLE
Screen rotation has bugs on Android

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#467] opened 2020-04-11 12:57 UTC
Concerning orientation of screens by rotating your phone:

- on Android, there are two bugs: switching from portrait to landscape works, but there a some parts missing in the lower part of the screen. Switching back from landscape to portrait leaves the lower 40% of the screen blank, it looks like cut off.

Bug can be seen in live-mode and in build apps.

BTW: changing screen orientation (=rotating the phone) on iOS works great!

**Comment by josmas** [comment] 2020-04-11 17:16
Hi @kezb765 thanks for your report. We are aware of the issues, that's why we've launched support for iOS only at the moment:
<img width="269" alt="ios_only" src="https://user-images.githubusercontent.com/194925/79050217-81ff2080-7c20-11ea-9849-1f9b47468c5b.png">

**Comment by josmas** [comment] 2020-05-08 21:10
closing this one as duplicate of https://github.com/thunkable/thunkable-issues/issues/490 cause there's more in the other ticket. Thanks!

**Closed by josmas** 2020-05-08 21:10 UTC
Labels: enhancement, planned work
