### ISSUE TITLE
Multiple block selection

### ISSUE THREAD

**Issue by gepponline** [thunkable/thunkable-issues#930] opened 2021-05-27 10:16 UTC
In thunkable X
I have to move several blocks to another position of the screen. To do so, I have to move them one by one.
It would be nice to have the ability to select multiple object and move them along the block screen with only one movement.

**Comment by jane-d-alt** [comment] 2021-06-03 08:50
Duplicate of #911

**Closed by jane-d-alt** 2021-06-03 08:50 UTC
Labels: duplicate, enhancement, to be considered (no ETA)
