### ISSUE TITLE
Design Request : Lengthen Screen bar

### ISSUE THREAD

**Issue by Advaitt** [thunkable/thunkable-issues#965] opened 2021-06-12 12:26 UTC
Hi , Is really difficult to navigate between Screens when designing due to the small size of the screen bar. I think Making it larger would be a piece of cake and hope you do it soon.
Pictures to support : 
https://user-images.githubusercontent.com/72341138/121775804-591d4700-cba7-11eb-8892-daa9d673c6df.png

**Comment by domhnallohanlon** [comment] 2021-06-17 10:27
Thanks for the feedback @Advaitt - if you use the Drag and Drop editor you get a heads-up view off all your screens in the design tab.

<img width="1440" alt="Screenshot 2021-06-17 at 11 24 59" src="https://user-images.githubusercontent.com/3117345/122379312-a8c09180-cf5e-11eb-90ee-a4bdd6dbb936.png">

You can pan and zoom freely and it's generally a lot easier to work with. 

cc: @SkulaMesterHU

**Comment by Advaitt** [comment] 2021-06-17 12:04
> Thanks for the feedback @Advaitt - if you use the Drag and Drop editor you get a heads-up view off all your screens in the design tab.
> 
> <img alt="Screenshot 2021-06-17 at 11 24 59" width="1440" src="https://user-images.githubusercontent.com/3117345/122379312-a8c09180-cf5e-11eb-90ee-a4bdd6dbb936.png">
> 
> You can pan and zoom freely and it's generally a lot easier to work with.
> 
> cc: @SkulaMesterHU

@domhnallohanlon  yes this is very helpful but what i wanted is that you can lengthen then bar on top which shows screen 1 screen 2 , screen 3 to width 💯 100 % then to go to another screen will be much easier
 if we have a lot of screens

**Comment by jane-d-alt** [comment] 2021-06-25 09:47
Closing as this is a duplicate of #776. Thanks!

**Closed by jane-d-alt** 2021-06-25 09:47 UTC
Labels: duplicate
