### ISSUE TITLE
Renaming a project from the projects list should not open the project

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#963] opened 2021-06-12 07:19 UTC
### Platform
Thunkable X, Chrome browser, OS X

### Steps to Reproduce
1. If I click the pencil icon in the [projects list](https://x.thunkable.com/projects) to rename a project and then click to highlight part of the project name, the project opens to the Design tab.

### Expected Behavior
Clicking within the text input field should not open the project.

### Actual Behavior
The project opens. This doesn't happen every single time but probably 25% of the time I try to rename a project.

```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="451" alt="Screen Shot 2021-06-12 at 12 19 30 AM" src="https://user-images.githubusercontent.com/10355498/121768670-3aba3b80-cb14-11eb-882a-6410da9f6e1d.png">

**Comment by domhnallohanlon** [comment] 2021-06-17 09:59
Thanks for reporting this - I wasn't able to reproduce this in Chrome on OS X...I tried manually selecting and using keyboard shortcuts. 

![rename_and_highlight](https://user-images.githubusercontent.com/3117345/122375079-d1df2300-cf5a-11eb-9f28-7bfd41f36a67.gif)

Was this a temporary thing?

**Comment by jane-d-alt** [comment] 2021-07-09 10:51
Hi Tatian,

Since you didn't follow up on Domhnall's comment, and we can't reproduce this behavior, we are going to close this issue.

If this behavior still affects you, please re-open this conversation and let us know:
- What version of Thunkable you are using
- What browser you are using
- What OS your computer uses

Thanks!

**Closed by jane-d-alt** 2021-07-09 10:51 UTC
Labels: cannot reproduce
