### ISSUE TITLE
(for Thunkable X) Custom blocks (aka extensions)

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#74] opened 2018-08-15 06:01 UTC
Creating your own blocks is not an easy task for novice users, but it would be interesting for experienced users, especially if this mechanism provided access to at least React Native.  The community should have some tool to extend the functionality of Thunkable X. Otherwise, the development of the platform will not happen quickly enough.

**Comment by jane-d-alt** [comment] 2021-01-08 14:43
duplicate of #20

**Closed by jane-d-alt** 2021-01-08 14:43 UTC
