### ISSUE TITLE
Live Test Apps (Android & iOS)

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#396] opened 2020-02-21 18:41 UTC
Relating to Thunkable X.
Relating to Thunkable X Live View App.

Would it be possible to remove the top information bar from Thunkable X Live for iOS and Android, and specifically for iOS to remove the banner at the bottom of an app saying to check back for help and that the project is live.

This is a pain when trying to scale components and see how it would actually look, especially when doing the background colour/image of a screen, not a column, as this effects the task bar. 

The banner at the bottom of iOS Apps (attached below) is in the way, maybe have a small close button to make it drop down.

For the buttons on the top to say "view code" or "back" are useful, but I think could be implemented with gestures. Maybe some sort of drop down menu or something to go back? 

Thanks,

Eoin.

![463b0bb8239dba2ce7822039cec699120b6ebe88](https://user-images.githubusercontent.com/48634511/75061833-75d8cb80-54d9-11ea-9e3c-4dc1ec0d470e.jpeg)

**Comment by josmas** [comment] 2020-02-22 15:10
Thanks for your report; there's a bit more discussion on this topic at #326, so I am going to close as duplicate and we can keep track of both in the other issue. Thanks!

Duplicate of #326

**Closed by josmas** 2020-02-22 15:10 UTC
