### ISSUE TITLE
Can't scroll in the blocks sectiom

### ISSUE THREAD

**Issue by GMShack11** [thunkable/thunkable-issues#757] opened 2020-11-29 07:16 UTC
I can't scroll in the blocks section on any of my apps, 
I can only Drag the scrollbar to scroll,
```I hope you can fix this issue soon

 Thank you

**Comment by domhnallohanlon** [comment] 2021-05-07 13:56
Hi @GMShack11 - I'm not able to reproduce this behaviour on my end. 

Are you trying to use Thunkable from a mobile device?

**Comment by jane-d-alt** [comment] 2021-05-17 09:11
Hi there,

Is your desired behavior that you can pan-to-scroll or use a scroll wheel to navigate in the Blocks tab?

**Comment by GMShack11** [comment] 2021-05-17 09:31
I can't use the scroll wheel to navigate in the blacks tab @jane-d-alt

**Comment by jane-d-alt** [comment] 2021-06-02 07:34
This issue overlaps with #706, so we will close this as a duplicate. Thanks for the request!

**Closed by jane-d-alt** 2021-06-02 07:34 UTC
Labels: duplicate, enhancement
