### ISSUE TITLE
(Thunkable X) After platform updates, text blocks with a space become empty

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#385] opened 2020-02-13 06:31 UTC
After updating the platform I see that this space is removed from text blocks with one space and the text block becomes empty, which breaks all the algorithms that should use this space!

This may also be the case when a string consists of multiple whitespace characters, rather than just one space.

**Comment by josmas** [comment] 2020-02-13 09:45
Hi @AlexITMan thanks for your report. If you don't mind, I am going to close it as a dup, but you can follow up on progress here #345 

Duplicate of #345 Thanks!

**Closed by josmas** 2020-02-13 09:45 UTC
