### ISSUE TITLE
Canvas not working with a data viewer in previous screen

### ISSUE THREAD

**Issue by Govardhanan-btp** [thunkable/thunkable-issues#939] opened 2021-06-01 06:49 UTC
Platform - Thunkable X

### Steps to Reproduce
1. Create a stack navigator with 2 screens
2. Place a data viewer grid in screen 1 and bind it with a source
3. Place a canvas in screen 2
4. Add a block to navigate to screen 2, when an item is clicked in data viewer grid of screen 1.

### Project Link
https://x.thunkable.com/copy/3ca641c4a30f9ed1204c4de69097b843

### Expected Behavior
Canvas have to displayed 

### Actual Behavior
Canvas will not be displayed as long as I have a data viewer grid in previous screen. Once I delete it, it actually shows up. 

```
  STACK TRACE AND/OR SCREENSHOTS
```
![Issue image_1](https://user-images.githubusercontent.com/83805735/120278904-77479500-c2d3-11eb-83a9-714722666aaf.png)

![Issue image_2](https://user-images.githubusercontent.com/83805735/120278921-7c0c4900-c2d3-11eb-8a88-2dc1391e1cdc.png)

**Comment by tatiang** [comment] 2021-06-01 07:01
I was able to reproduce this issue with the project linked above in Thunkable Live on an iPhone 11.

**Comment by Govardhanan-btp** [comment] 2021-06-02 10:40
Hello!
Any idea of when this bug will be resolved? Just asking to plan things ahead, as our app will be able to function fully only with canvas and data sources together. 

**Your immediate attention will be very much appreciated. Thanks a ton in advance.**

**Comment by SkulaMesterHU** [comment] 2021-06-02 20:34
@Govardhanan-btp 
Well, there are a lot of bugs waiting to be fixed, which are very important ones. I would say it could take even months, so you have better finding a way to get around this bug.

**Comment by jane-d-alt** [comment] 2021-06-04 08:46
Hi there,

Thanks for letting us know about this. I have a few follow up questions:

Do you experience this behavior with other navigators, or just the stack navigator?
Do you experience this behavior with projects built in the snap-to-place UI, or just the drag-and-drop UI?
Does you see this behavior if you add a Data Viewer List to the project?
Do you see this behavior if the screen with the Canvas is displayed before the screen with the Data Viewer?

**Comment by Govardhanan-btp** [comment] 2021-06-05 04:11
Hello Jane! Thanks for the follow-up. Below are the answers. 

**Do you experience this behavior with other navigators, or just the stack navigator?**
Yes, the same happens in all the navigators. In fact, this happens even without navigators, even when screens are placed one after the other in simpler fashion. 

**Do you experience this behavior with projects built in the snap-to-place UI, or just the drag-and-drop UI?**
Yes, I checked with Snap-to-Place UI also. There too, the bug persists. 

**Does you see this behavior if you add a Data Viewer List to the project?**
Yes, the problem persists even when data Viewer List is added. I guess, the problem is with binding with a data source. 

**Do you see this behavior if the screen with the Canvas is displayed before the screen with the Data Viewer?**
No, when the screen is displayed before the screen with the data Viewer, it works fine. But, it has to be the first screen of the project. Even if there is some other navigators with screen that have data viewers, the screen after that is not displaying canvas. 

Hope this answers all your questions. For assisting you in this, I have made all the changes in the shared project for seeing the results of all these answers easily.

**Comment by Govardhanan-btp** [comment] 2021-06-05 04:20
**Well, there are a lot of bugs waiting to be fixed, which are very important ones. I would say it could take even months, so you have better finding a way to get around this bug.**

Hmm, from our point of view, this bug is something important as it has paused our activity. We understand, there are so many many bugs in your environment that has to be dealt with. But in no way, asking someone who reported a bug in your thing to get around with the same is right even for a while. I am sorry if this hurts you. 

You grow, we grow. We grow, you grow. 
Definitely, with much more questions from your side, we are here to work along with you to atleast do the trouble-shooting to narrow down on the problem exactly. That is how we can help you with, and we have did the same. 

Love,
Govardhanan.

**Comment by SkulaMesterHU** [comment] 2021-06-05 06:32
Well, thank you for your answer.

I didn't say that this bug isn't so important one, I understand that it paused your activity. I didn't want to hurt you, I just have the same experience: I have reported a lot of bugs as well, but I didn't even get a reply, and because of that I commented that it can take months as well.

I know that the team is working hard to build an awesome platform, but because of all this I just suggested finding another way of doing that instead of waiting for the fix, as in my observation a fix could take even months.

Anyway, sorry again and I hope that this will be fixed ASAP and you can continue developing your app.

**Comment by jane-d-alt** [comment] 2021-06-09 06:22
Thanks for answering those questions. I've written an internal report and shared it with the team.

**Comment by Govardhanan-btp** [comment] 2021-06-09 10:09
@SkulaMesterHU 

I didn't know that you are also developing. I thought you are one among the Thunkable team. I am sorry about that. Yes, it is taking a long time for the bugs to be closed and I see hundreds of open threads in github. Lets hope the team works a bit more fast to help people who are using their platform. 

I wasn't able to find a solution for this, as both canvas and data sources are vital in our app. But, thanks for understanding and standing by our side. Thanks for your idea too!

Have a good day!

**Comment by Govardhanan-btp** [comment] 2021-06-09 10:10
@jane-d-alt 

Thanks for the response. It would be really really helpful, if you can come up with a approx. timeline on when the issue will be closed after discussing with your internal team. Your help in this would be much appreciated. 

Thanks a ton in advance.

**Comment by SkulaMesterHU** [comment] 2021-06-11 17:29
@Govardhanan-btp imagine, I have the same bug in my app, it is very annoying. Did you solve it or waiting for the fix?

**Comment by SkulaMesterHU** [comment] 2021-06-15 07:22
Hi @jane-d-alt,

I wonder when the fix for this comes? It would be urgent, because one of the key features of my app can't be used.

Thanks.

**Comment by SkulaMesterHU** [comment] 2021-06-15 11:28
@Govardhanan-btp the fix is coming: 
<img width="243" alt="image" src="https://user-images.githubusercontent.com/62901396/122045051-86533a80-cddd-11eb-9bba-01d3b5a1c2c2.png">

**Comment by Govardhanan-btp** [comment] 2021-06-15 11:31
@SkulaMesterHU Wow, thats amazing! Actually, i was waiting for it for a long time, as I was tired of getting it fixed. Thank god, we are getting it soon. Hope this helps you also close your project soon. 🙌

**Comment by SkulaMesterHU** [comment] 2021-06-15 11:40
@Govardhanan-btp UPDATE: The fix isn't coming, @domhnallohanlon was wrong.

**Comment by Govardhanan-btp** [comment] 2021-06-15 11:48
@SkulaMesterHU  Okay, now this sounds like a reality. 😂 Anyhow, Happy that they are working on that. Lets see.

**Comment by domhnallohanlon** [comment] 2021-06-15 12:08
Just to clarify here - I was referring to a fix this is coming soon for
#937 which I was testing rather than #939

Thanks

**Comment by Govardhanan-btp** [comment] 2021-06-28 10:30
I have been informed by @jane-d-alt that, the fix has been released. But still I face the same problem. It has been a month since we posted the bug. I kindly request you to please take immediate action in rectifying this.

Thanks a ton in advance. 

Govardhanan.

**Comment by jane-d-alt** [comment] 2021-07-14 09:46
A fix has been published for this behavior. You can now view your Canvas which is in a Navigator alongside a Data Viewer on the web, and when you have downloaded your app to a device. An update to the Thunkable Live app will follow shortly.

We appreciate your patience as we worked on this issue. Thanks to all who reported!

**Closed by jane-d-alt** 2021-07-14 09:46 UTC
Labels: bug, question
