### ISSUE TITLE
User Interface feature or Device block to disable sleep mode while app is running

### ISSUE THREAD

**Issue by eputkonen** [thunkable/thunkable-issues#436] opened 2020-03-21 20:39 UTC
**Is your feature request related to a problem? Please describe.**
I am creating a timer that would be used for over an hour, but when my devices "sleep" after 3 minutes...the app basically closes and the timer stops.  I don't want to ask users to modify their sleep mode.  It would make more sense to temporarily deactivate sleep mode while the app is running,.

**Describe the solution you'd like**
A user interface item or Device bock item that will disable the sleep mode while the app is running.

**Describe alternatives you've considered**
I have looked through the help and conversation.  People have suggested changing things on the screen (which did not work for me...or I was not doing it right) or playing video to keep it from sleeping, but this could be a Device block and solve the issue for all who want their apps to continue to run until closed. 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by josmas** [comment] 2020-03-22 16:41
Thanks for your request; your point is very valid, we should not rely on workarounds for this, and we will eventually provide a way to do it. For now, we will be tracking progress [here](https://github.com/thunkable/thunkable-issues/issues/329), so closing this one out as a dup. Thanks!

Duplicate of #329

**Closed by josmas** 2020-03-22 16:41 UTC
