### ISSUE TITLE
Web Api "PATCH"

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#393] opened 2020-02-21 00:26 UTC
**Is your feature request related to a problem? Please describe.**
I'm triying to use Firestore web api 

**Describe the solution you'd like**
PATCH method to the web API component

**Which platform are you asking for?**
Thunkable X

**Comment by amblemind** [comment] 2020-11-09 19:06
Upvote: This is a dup of https://github.com/thunkable/thunkable-issues/issues/130 and should be merged/deleted.

**Comment by josmas** [comment] 2020-11-10 16:46
closing as 
Duplicate of #130

**Closed by josmas** 2020-11-10 16:46 UTC
Labels: enhancement, follow up
