### ISSUE TITLE
Allow us to edit projects on out phone.

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#883] opened 2021-04-29 11:10 UTC
Hi would like to be able to edit projects on my phone.
This wil speed up the development of My project.
This Will also allow me to work on my projects while I am on a vaccation and don't have My Chromebook with me.
OR if i don't have wifi then i can edit My projects on my phone through 4/5G

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by josmas** [comment] 2021-04-29 14:05
Duplicate of #862

**Closed by josmas** 2021-04-29 14:05 UTC
