### ISSUE TITLE
Loading_Icon and GIF Images not working

### ISSUE THREAD

**Issue by lamagalhaes** [thunkable/thunkable-issues#614] opened 2020-07-27 15:05 UTC
(screen1) If you put an `Loading_Icon` in a splash screen, even with timer or block `wait x seconds` in a `screen opens` block, nothing in this block works.

(screen2) GIF images is not working too.

### Platform
X Android

### Steps to Reproduce
Is pretty clear in the project.

### Project Link
https://x.thunkable.com/copy/656079014da19ace384abaa95b8b94f0

### Expected Behavior
Blocks to run after time expires and GIFs to work.

### Actual Behavior
Blocks don't run.
GIFs don't work.

**Comment by MrMazzone** [comment] 2020-07-27 18:52
This is weird.  I can confirm, animated gif files are not working and loading icon breaks the `navigate to screen` block. 

This issue is only on mobile (iOS and Android).  Both properly function on Web.

**Comment by josmas** [comment] 2020-07-31 12:42
Thanks for the report, guys!

Can I confirm, the first time the Companion opens you can see the loading icon but nothing happens until you click the button to screen2. But if you click the button in screen 2 to go back to Screen 1, the timer starts working; is that correct?

Also, I can see that the gifs are not animating.

**Comment by lamagalhaes** [comment] 2020-07-31 12:44
Hi Jos,

Exactly. That's what happens.

Tks

Em sex, 31 de jul de 2020 09:42, Jos <notifications@github.com> escreveu:

**Comment by josmas** [comment] 2020-07-31 12:46
Thanks @lamagalhaes We'll have a look.

**Comment by athornock84037** [comment] 2020-08-20 16:53
@josmas any idea when animated gifs will work? I'm waiting to publish an app on this...that and updating the code for the new app store.

**Comment by josmas** [comment] 2020-08-27 20:54
All, animated gifs will be fixed in version 216 (dropping as soon as we get approval for iOS).

The issue with the icon is a tricky one. It only happens on Android and we've tracked it down to an issue with the underlying library. For some reason it looks like the icon is `stealing` focus so the `opens` call is skipped, but this only happens on Android, whilst web and iOS work just fine, as expected.

This is not a real fix, but for the use case on here, if you change `opens` to `starts` the icon will not get in the way. Because you are changing screens, both methods will (or should) trigger in any case.

As a longer term solution, we have a pending upgrade of the navigation library, but this task depends on a few other tasks, so we have no ETA at the moment. Thanks all for your patience!

**Comment by jane-d-alt** [comment] 2021-04-23 13:34
Hi there,

This behavior has been resolved and now a the blocks in the 'When Screen Opens' block of a Screen with a Loading Icon will execute as expected. Apologies for not following up when this behavior was originally resolved. Thanks to all who reported this behavior.

**Closed by jane-d-alt** 2021-04-23 13:34 UTC
Labels: bug, follow up, moved
