### ISSUE TITLE
After downloading and installing, the app crashes!

### ISSUE THREAD

**Issue by balancedkitchen** [thunkable/thunkable-issues#187] opened 2019-07-13 15:05 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
My App works fine in Live Preview.
But no chance when I download the App.
Can anybody help me?
photos of error:
![error](https://user-images.githubusercontent.com/46844220/61173187-9a121880-a598-11e9-8f6b-bd599336a3ac.png)
![error1](https://user-images.githubusercontent.com/46844220/61173188-9e3e3600-a598-11e9-9816-d94fe8eb3e14.png)

**Comment by mark-friedman** [comment] 2019-07-13 18:02
@balancedkitchen, That's an unusual error.  Can you post a link to your app for us to try?  Also, have you been able to run downloaded APKs from Thunkable ✕ previously?  Can you try an download and run another app?  Is it possible that you've run out of space on your device?

**Comment by balancedkitchen** [comment] 2019-07-14 06:19
I did tests on several different models of devices. All of them had spare space in surplus. I tested another application from my projects (created months ago). There was no problem with him. Here's a link to the app: https://x.thunkable.com/copy/a3a86dcb6a719bf001d1fb97c52898bc

**Comment by balancedkitchen** [comment] 2019-07-14 14:45
I don’t know if you have already fixed the problem, but I have found the following:
After repeatedly downloading the app on one occasion, they are installed and run well.
I hope this information helps you.

**Comment by mark-friedman** [comment] 2019-07-15 20:14
Unfortunately, I can't seem to reproduce the problem.  I tried downloading and installing the app on a couple of devices and an Android emulator and didn't see the problem that you were having.  Can you tell me what devices your had problems with?  Maybe the issue is specific to a particular class of devices.

**Comment by balancedkitchen** [comment] 2019-07-19 05:39
I tested these devices:
lenovo 6010A
Samsung Galaxy A7
Samsung Galaxy Note9
Xiaomi Redmi Note 6 Pro
Xiaomi Mi 9T
Now there is no problem!
Thanks!

**Comment by mark-friedman** [comment] 2019-07-19 16:15
Thanks, @balancedkitchen!  I'm glad that the problem appears to have gone away, at least for now.  I'll close this issue.

**Closed by mark-friedman** 2019-07-19 16:15 UTC
