### ISSUE TITLE
Sound does not stop when exiting Thunkable Live preview

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#774] opened 2020-12-12 22:10 UTC
### Platform
Thunkable X

### Steps to Reproduce
1. Open a project on the Thunkable Live app on an iPhone 11
2. Play a sound
3. Press the "Back" button to exit the project preview.
4. The sound keeps playing until I force-quit the Thunkable Live app.

### Expected Behavior
The sound should stop.

### Actual Behavior
It doesn't.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment] 2020-12-21 13:06
closing this as a 
Duplicate of #765

**Closed by josmas** 2020-12-21 13:06 UTC
