### ISSUE TITLE
(for Thunkable X) Copy/Paste blocks between projects

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#73] opened 2018-08-15 05:50 UTC
Blockly allows to save blocks in local storage.  If you create the same mechanism in the Thunkable X IDE, you will be able to save the blocks in the local storage and copy them between projects.

**Comment by jane-d-alt** [comment] 2021-01-08 14:42
duplicate of #51

**Closed by jane-d-alt** 2021-01-08 14:42 UTC
