### ISSUE TITLE
Control photo quality

### ISSUE THREAD

**Issue by jaredgibb** [thunkable/thunkable-issues#710] opened 2020-10-18 11:58 UTC
**Is your feature request related to a problem? Please describe.**
I am frustrated that each image I send to cloudinary is <4mb often. this is due to the phone i am using. this results in a lot of bandwith usage with cloudinary and having to resize images to compress them for network transfer

**Describe the solution you'd like**
I would like to be able to control resolution/image quality when uploading/taking photos. this is possible when sending a photo from the iphone but not while taking the photo. 

**Describe alternatives you've considered**
Currently i resize all photos using the cloudinary api. this results in compression from 4mb to 50kb

**Which platform are you asking for?**
ThunkableX

**Comment by AmigoDeluxe** [comment] 2020-11-15 09:05
Duplicate request? https://github.com/thunkable/thunkable-issues/issues/224

**Comment by jaredgibb** [comment] 2021-02-21 17:34
Hey @josmas. I wonder if your team has had a chance to talk about this one? I’d ao, any news?

**Comment by josmas** [comment] 2021-02-28 23:00
this is indeed a Duplicate of #224
There's more info there so closing down this one. Please follow discussion there.

**Closed by josmas** 2021-02-28 23:00 UTC
Labels: enhancement, to be considered (no ETA)
