### ISSUE TITLE
Device Screen Width Block not working on Live Test

### ISSUE THREAD

**Issue by cesomaggio** [thunkable/thunkable-issues#784] opened 2020-12-21 13:41 UTC
### Platform
✕ Live Test

### Issue/Request Origin
I´m Thunkable user "caminostudio". I used the Device Screen Width Block to create a responsive animation in my web app. It was working, but not anymore on Live Test. Then, I can´t test a new version of the animation.  

### Steps to Reproduce
1. Access demo project Demo bug Device Screen Width (https://x.thunkable.com/projectPage/5fdd110bacd841001152e694), click "Live Test" and click on the link "Preview as a responsive web app"
2. Access published web app: https://thunkable.site/web-build/index.html?webAppId=86mOTv_uc
3. Compare the different results.

### Project Link
https://x.thunkable.com/projectPage/5fdd110bacd841001152e694

### Expected Behavior
"Screen width" block returns screen width. 

### Actual Behavior
On Live Test, "screen width" block always return "249".

  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment] 2020-12-21 14:56
Thanks for the report @cesomaggio 

@TingC any idea as to what might be going on? I can reproduce with the included project. Thanks!

**Comment by jane-d-alt** [comment] 2021-05-24 12:11
Hi there,

It looks like this behavior has been resolved. The linked project page now returns 375 and the linked web app now returns 1680 on my device.

We will close this issue now. Apologies for not following up when this behavior was originally resolved.

Thanks for reporting!

**Closed by jane-d-alt** 2021-05-24 12:11 UTC
Labels: bug, follow up, moved, triage
