### ISSUE TITLE
Videos don't restart / freeze once played

### ISSUE THREAD

**Issue by realmisterfish** [thunkable/thunkable-issues#463] opened 2020-04-09 01:18 UTC
### Platform
Android X iOS

### Issue/Request Origin
My app

### Steps to Reproduce
1. Add a video element or Cloudinary hosted video URL
2. Play the video once to completion on the app
3. Try to a) restart the video or b) scroll anywhere in the video

### Expected Behavior
Expected behavior is that you can restart the video or scroll anywhere in the video once you've watched it once

### Actual Behavior
Nothing, the video is essentially locked.
```

Please help with this, it's been over 1 month and the videos I'm uploading require the user to re-watch them for clarity.

**Comment by josmas** [comment] 2020-04-10 12:05
Thanks for your report @realmisterfish 
We are keeping track of it already so closing this one.
Duplicate of #424

**Closed by josmas** 2020-04-10 12:05 UTC
