### ISSUE TITLE
DataSource in copied project is messed up

### ISSUE THREAD

**Issue by wolberd** [thunkable/thunkable-issues#796] opened 2020-12-30 22:37 UTC
I have an app with a Data Viewer List and DataSource connected to a Google Sheet. 
When I make a copy of the app, and then view data in the Data Source in the properties panel, it doesn't show the data and the button to synch the data is gone as well.

**Comment by josmas** [comment] 2021-01-11 17:51
Hey @wolberd (long time, by the way!).

Copies do not keep the connection to data sources, and that is by design (in case you share your app, you don't want to share your credentials). There is a bit of discussion about that design (pros and cons) here. Closing this as a dup for now. 
Duplicate of #654

**Closed by josmas** 2021-01-11 17:51 UTC
