### ISSUE TITLE
Corrupted project file?

### ISSUE THREAD

**Issue by fastpipe** [thunkable/thunkable-issues#56] opened 2018-08-02 17:57 UTC
Hi, with some of my projects I have severe problems:
Error, when
- download apk 
- generate link
- copy

all does not work.

e.g. my project htmlLineAsset in my account approedu@gmail.com

has this problem.
Question to the developers: Is it a corrupted file? And how could I fix it (cannot copy or share!!)

**Comment by mark-friedman** [comment] 2018-08-09 23:54
This is more or less a duplicate of #55, so I'm closing it.

**Closed by mark-friedman** 2018-08-09 23:54 UTC
