### ISSUE TITLE
Fit Contents not displaying as expected on Web Preview with nested components

### ISSUE THREAD

**Issue by domhnallohanlon** [thunkable/thunkable-issues#601] opened 2020-07-17 16:50 UTC
### Issue/Request Origin
Community
https://community.thunkable.com/t/problems-with-component-alignments-on-browser-web-app/683909/7?u=domhnallohanlon

### Steps to Reproduce
1. Layout components with their height set to "Fit Contents" are behaving like their height is "Fill Container"
2. 
3.

### Project Link
https://x.thunkable.com/copy/efcd0eaf20628bab6a8dab094198a208

### Expected Behavior

(The row has 3 px padding for illustration purposes)
![Screenshot_20200717-174520](https://user-images.githubusercontent.com/3117345/87811068-f8ca3c00-c855-11ea-9538-71acd76700eb.jpg)

### Actual Behavior
<img width="454" alt="Screenshot 2020-07-17 at 17 47 41" src="https://user-images.githubusercontent.com/3117345/87811036-e3551200-c855-11ea-8234-191909b12a21.png">

**Comment by cesomaggio** [comment] 2020-07-17 21:34
Hi! This problem is also happening with published apps. It's not just a problem on Web Preview. Unfortunately, my web-app is crashed since yesterday. Thanks for the help!

**Comment by gobassky** [comment] 2020-07-19 01:29
Not sure if this is related: the alignment within the text label components also does not work on web preview (as a responsive web app) and published web app. It is always justified left no matte what properties were used.

**Comment by domhnallohanlon** [comment] 2020-07-21 12:39
@cesomaggio - when you say Published apps do you mean "Published as a Web App"? I tried to reproduce this yesterday and wasn't able to. 

Do you mind sharing an example with us please?

**Comment by domhnallohanlon** [comment] 2020-07-21 12:41
@gobassky I'm not sure if sizing and alignment are related to be honest. 

Let's focus on the sizing issue here and if that doesn't resolve the alignment problem too then we can create a dedicated thread for that. 

Thanks

**Comment by TingC** [comment] 2020-07-23 20:41
@cesomaggio, we just released a fix regarding this layout issue, so we'are going to close this issue now, but please let us know (open tickets and provide an example project showing the issue you're experiencing) if you still experiencing some other layout issue, and we're happy to help and improve.

@gobassky, yes, I agree with @domhnallohanlon that this ticket is about the alignment issue, so we'll be focusing on the layout issue here. If you could open a ticket and provide some details (an example project link showing the issue is the best) to help us identify what you mean, that would be very helpful.

Thank you all  : )

**Closed by TingC** 2020-07-23 20:41 UTC
