### ISSUE TITLE
Speech Recognition still doesn't work correctly. 

### ISSUE THREAD

**Issue by 72drenton** [thunkable/thunkable-issues#1047] opened 2021-10-29 17:10 UTC
I can confirm that the speech recognition only works once in your project. If I Live Test on an iPhone, it recognizes and displays the speech once. But after that, it seems to ignore the event. I even tried it with the advanced version of the block and it failed similarly and did not display an error nor speech results.

**Comment by josmas** [comment] 2022-01-07 13:56
Duplicate of #1046

**Closed by josmas** 2022-01-07 13:56 UTC
