### ISSUE TITLE
Images don't appear on buttons, sprites

### ISSUE THREAD

**Issue by bromanous** [thunkable/thunkable-issues#574] opened 2020-06-23 21:53 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕

### Issue/Request Origin
Myself

### Steps to Reproduce
1. Run this app in Web Testing:
https://x.thunkable.com/copy/a0ae350f296bb5083336b3b95f2f2852

### Project Link
https://x.thunkable.com/copy/a0ae350f296bb5083336b3b95f2f2852

### Expected Behavior
Images didn't appear.

### Actual Behavior

Please see this example:
https://x.thunkable.com/copy/a0ae350f296bb5083336b3b95f2f2852

The background image on this Button does appear in the Thunkable Live companion app, and would appear in a downloaded and installed app. However, the image does not appear when Web Testing the app, and would not appear when the app is published as a web app.

**Comment by weihuali0509** [comment] 2020-06-23 21:57
Thanks for reporting this issue. Did this happen recently?

**Comment by bromanous** [comment] 2020-06-23 22:07
Yes. starting yesterday. It is actually the same issue reported in 
https://github.com/thunkable/thunkable-issues/issues/573

I just found out that we both created bug reports but it is the same issue.

**Comment by weihuali0509** [comment] 2020-06-23 22:17
Duplicate of https://github.com/thunkable/thunkable-issues/issues/573

**Closed by weihuali0509** 2020-06-23 22:17 UTC
