### ISSUE TITLE
(Thunkable X) Crash in Live app on Android when trying to set a non-existing property using an "any" block

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#284] opened 2019-10-23 07:35 UTC
This causes a crash on Live on Android 8.1

![изображение](https://user-images.githubusercontent.com/20015046/67368677-66c02c00-f580-11e9-9659-def4fef9dbdf.png)

**Comment by mark-friedman** [comment] 2019-10-23 16:41
@AlexITMan, I assume that Text_Input1 is a Text Input component in your example.  Is that right?

**Comment by AlexITMan** [comment] 2019-10-23 18:07
Yes. Text_input1 - this input component. But you can substitute the Button, Date Input or another - will also take place crash.

**Comment by mark-friedman** [comment] 2019-10-24 17:17
But I assume that a Label will work.  So the issue is when you use an incorrect component as an input to a block that expects a particular component type, in this case a Label.  I agree that crashing is bad behavior in this case.  Do you have an idea for what behavior you would like to see?  Would just ignoring the block be ok?

**Comment by AlexITMan** [comment] 2019-10-26 12:00
I think you need to either ignore it, or change the Text property value for all components for which it exists.

I like the second option, when using a single unit, you can change the properties of all components for which this property exists. For example, if you select the type of property and Input Text Border Width, then with the help of this unit can be set up for border Button, Label, and all other components for which the property is used.

**Comment by AlexITMan** [comment] 2019-10-26 18:48
Mark, I think because of the polymorphism can simply extend the functionality of the interface components. You do not need to create blocks for all components. Suffice it to expand the list of properties in the blocks set and get Any Component.

**Comment by jane-d-alt** [comment] 2021-01-15 15:29
This kind of block will now fail silently/be ignored. We'll close this issue now; apologies for not following up here when this behavior was originally resolved.

**Closed by jane-d-alt** 2021-01-15 15:29 UTC
