### ISSUE TITLE
Cloud Variable and Realtime DB Read/Write Inconsistent Across Platforms

### ISSUE THREAD

**Issue by amblemind** [thunkable/thunkable-issues#500] opened 2020-05-06 03:47 UTC
### Platform
✕ web, ✕ Android downloaded, or ✕ iOS downloaded?

### Issue/Request Origin
Self Found and Reported

### Steps to Reproduce
1. Copy this app: https://x.thunkable.com/copy/73ac5ca0dad5b6c27322b35845d8accb
2. Enter a key
3. Press the buttons
4. Compare against the matrics in the image

### Project Link
https://x.thunkable.com/copy/73ac5ca0dad5b6c27322b35845d8accb

### Expected Behavior
I expect to see 'success' in the console label after entering a key and pressing each of the 4 buttons in order from top to bottom. 

### Actual Behavior
Some test cases pass, others either return null or say the function is not defined. 

A matrix is attached with the test results for each platform. 

<img width="860" alt="Screen Shot 2020-05-05 at 10 41 54 PM" src="https://user-images.githubusercontent.com/45864164/81136595-a8fbfa00-8f21-11ea-9fd5-d09b66729b63.png">

**Comment by weihuali0509** [comment] 2020-05-06 04:39
Looking into the issue 🚌

**Comment by weihuali0509** [comment] 2020-05-06 14:27
Can you try again to see if any of the red turns green today?

Related [issue](https://github.com/thunkable/thunkable-issues/issues/499)

**Comment by jaredgib** [comment] 2020-05-06 14:50
https://x.thunkable.com/copy/d8f58a4c275d4a5ce91a3e8e96adf745

I tried this with cloud variables and using the RealtimeDB today. With the live test via Chrome on my Macbook, no luck. I ran it on the Bluestacks android emulator on my Macbook, no luck. When I run the app with the live companion on my iPhone, it works. Waiting for the iPhone download now. will report back

***Code Below***
<img width="401" alt="Screen Shot 2020-05-06 at 10 42 20 AM" src="https://user-images.githubusercontent.com/58823942/81191692-4fc6b180-8f87-11ea-927f-1b0a60955ec3.png">

**Comment by Antoriccio9** [comment] 2020-05-06 16:23
From last night at midnight ( Italian Time), my app stopped working and I'm not anymore able to download any data from firebase. Jane from thunkable support told me that this morning you did a fix. For me the problem is still there. Both if I use the Companion on IOS od use the live tets on my pc.

**Comment by amblemind** [comment] 2020-05-06 16:42
I confirmed still seeing the issue on the Web Viewer. If it helps this was working all last week and on Monday. 

![image](https://user-images.githubusercontent.com/45864164/81204249-9b308e00-8f8e-11ea-836d-f8842e387b3a.png)

**Comment by Jocada12** [comment] 2020-05-06 17:05
yes, i have the same problem, firebase does not work, jane told me that it was solved, but unfortunately it still does not work, i have been testing the app that amblemind uploaded and it is exactly the same problem, i hope it can be solved. Thank you.

**Comment by isaacamannion** [comment] 2020-05-06 22:16
The issue is present after the hotfix for my app. Working on in Android version but not the web app. The web app is return undefined / null for database requests. Thanks.

**Comment by Bellacopia** [comment] 2020-05-06 23:09
Yes, Firebase DB does not work on downloaded apps (iOS and Android) while it works on Thunkable live (iOS and Android).
Now I am also experiencing problems with geocoding Google API (both in downloaded apps and in Thunkable live). Not a great moment...

**Comment by weihuali0509** [comment] 2020-05-06 23:49
Can someone confirm if your Android or iOS companion work with Firebase? You need to have the lastest version v185 from the store. 

Thanks,
Wei

**Comment by Jocada12** [comment] 2020-05-07 00:10
firebase doesn't work in thunkable live version 185
(Android).

**Comment by weihuali0509** [comment] 2020-05-07 00:23
@Jocada12 which part doesn't work? Sign In, DB?

**Comment by Jocada12** [comment] 2020-05-07 00:27
get/save in firebase

**Comment by weihuali0509** [comment] 2020-05-07 00:48
working on it, please give me 1~3 hours and I am trying to fix it :)

Wei

**Comment by Jocada12** [comment] 2020-05-07 00:50
Thanks

**Comment by 22rdhall** [comment] 2020-05-07 00:57
Can confirm with @Jocada12 . Get/save on v 185 not working.

**Comment by weihuali0509** [comment] 2020-05-07 02:09
Can you try on the web app first? The fix on Android companion/iOS companion are on the way ...

**Comment by GiovaneDuarte** [comment] 2020-05-07 02:26
também estou com problemas no firebase android pode me ajudar??

**Comment by GiovaneDuarte** [comment] 2020-05-07 02:31
I am also having problems in firebase android can you help me ??

**Comment by Jocada12** [comment] 2020-05-07 03:49
is amazing "firebase" now works in web app, and Android download. Thanks.

**Comment by isaacamannion** [comment] 2020-05-07 08:04
I'm having some success in the web app version.

**Comment by Sheaprdj** [comment] 2020-05-08 00:33
for those versions your testing is that through the thunkable live test? i tried mine as web app and no luck getting response from DB

**Comment by amblemind** [comment] 2020-05-08 22:02
My test case above is working now. 

However, in my app, I can say this works IF I add my own Firebase API keys. If the keys are left blank to use Thunkable's default, then any data I enter through the web viewer cannot be retrieved through my Android or iOS version of the app (and vice versa).

**Comment by jane-d-alt** [comment] 2021-04-16 13:36
Hi there,

Sorry for the delayed follow-up. Not being able to access the default Thunkable Firebase DB across web and devices is expected behavior, and we recommend using your own Firebase DB in development.

Since the original reported issue has been resolved, we will close this issue now. Thanks to all who contributed!

**Closed by jane-d-alt** 2021-04-16 13:36 UTC
