### ISSUE TITLE
Design feauture

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#384] opened 2020-02-13 01:14 UTC
**Is your feature request related to a problem? Please describe.**
When you get to have a lot of screens and components It becomes difficult to locate the component you want to edit or the screen. 

**Describe the solution you'd like**
instead of re opened all the screens within their components inside they'll stay the same as you left them.

**Describe alternatives you've considered**
an easy way to locate the component you have choosed to edit his design.

**Which platform are you asking for?**
Thunkable X

**Additional context**

**Comment by gre4twh1te** [comment] 2020-02-13 17:11
+1 for this - would be much easier to work with and I would also really appreciate if an item selected on the preview screen would automatically be focused in the left sidebar. It is really annoying to always have to search for the screen and item that you just selected.

**Comment by danielcoglitore** [comment] 2020-02-13 17:16
you said better than me !

**Comment by mark-friedman** [comment] 2020-02-13 17:30
I believe that this is a duplicate of #367.  If not, feel free to clarify and re-open this issue

**Closed by mark-friedman** 2020-02-13 17:30 UTC

**Comment by gre4twh1te** [comment] 2020-02-13 17:36
@mark-friedman this is similar to what I added here but not to what the initial post was. I think @danielcoglitore wants that the navigation elements would stay as you set them. For example I hide all screens sub-elements except for one screen then when I return to the design screen it should stay like that. Instead it will always expand all screen/navigator content.
