### ISSUE TITLE
Running the APP in the background

### ISSUE THREAD

**Issue by danibarzo** [thunkable/thunkable-issues#814] opened 2021-02-03 04:38 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to build an APP that needs to be running in the background. Currently thunkable does not support it.

**Describe the solution you'd like**
Many APPs will need to be running in the background like APPs for anti-theft, privacy, emergency, and security purposes

**Describe alternatives you've considered**
It's so hard to have a workaround to build an APP running in the background using thunkable, I think not possible

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by josmas** [comment] 2021-02-03 19:24
Thanks for the request; this has been requested before though, so closing as Duplicate of #459

**Closed by josmas** 2021-02-03 19:24 UTC
