### ISSUE TITLE
List indexing error

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#37] opened 2018-07-23 08:13 UTC
When the block is executed below in Thunkable Live X, "item 1" is shown as the first item. But sometimes Thunkable Live X on iOS 10.3, 11.3, 11.4 (on Android did not ckect it) as the first item shows "item2".

![default](https://user-images.githubusercontent.com/20015046/43064964-13357718-8e69-11e8-94d6-7bb00c7e4175.png)

**Comment by mark-friedman** [comment] 2018-07-26 16:55
@AlexITMan, We're having trouble replicating this error.  Could you create a simple app which consistently demonstrates the problem and share it here?

**Comment by AlexITMan** [comment] 2018-07-27 11:57
Hello Mark,

This error occurs about 1 time after 20-30 project launches in Thunkable Libe X in my project on the "Lists" screen.  

https://x.thunkable.com/projects/5b5865df01f90009ea99f0b9/srcTab2/designer 

On the "Dialogs" screen, I also use the "in list get #" block and was initially very surprised when I saw the white screen when I selected the last 3 button from the Alert list.  But then I understood the problem.  The "in list get #" block returned null to the "get property Text" block.

Alex

**Comment by AlexITMan** [comment] 2018-07-31 08:35
I once again got the wrong indexes of the list in Thunkable live X (iOS 11.4). All algorithms that use the block "in list get #" worked incorrectly in the project.  

![default](https://user-images.githubusercontent.com/20015046/43448116-b71432f0-94b5-11e8-9baa-b4f7ca0fa961.png)

It is interesting that at this failure the unit

![default](https://user-images.githubusercontent.com/20015046/43447016-1eb1120a-94b3-11e8-9faf-fe3f91c19e63.png)

did not work and in lblSelectedItemName there was a property value set in the properties panel - Label.

**Comment by mark-friedman** [comment] 2018-07-31 17:45
Alex, is there any chance you could create and share a much simpler app which consistently demonstrated the problem?  It's difficult diagnosing an issue in a large, complex app which only has the error ~4% of the time.

**Comment by AlexITMan** [comment] 2018-08-03 06:25
Mark, I will create a simple application for testing.

The thing is that one of the tasks I was trying to do was test the stability of Thunkable  Live X in a large application.  I noticed oddities that begin to appear in the project, the apk file that takes only 13MB.  It turns out that in theory the size of the application is limited to 50 MB, but in practice, applications with a much smaller size will work more or less stably.

**Comment by AlexITMan** [comment] 2018-08-03 07:10
Simple project for the test

https://x.thunkable.com/projects/5b63f581f549bbd59ddc1d98/project/properties/designer/

**Comment by mark-friedman** [comment] 2018-08-03 16:19
@AlexITMan, Just to be clear, does the test project you posted always show the error or is it still the case that it only shows the error in once in a while?

**Comment by AlexITMan** [comment] 2018-08-04 06:44
Below is a link to my last demonstration project (ver.10.8.2018) in which the indicated error appears almost stably in Thunkable Live X on iOS 11.4.

https://x.thunkable.com/projects/5b62ee9338e652270d9c53a9/project/properties/designer/

Perhaps this project is too big and heavy for Live X (on the last screen of the Sprite map, locally uploaded photos are not displayed when selecting items in the ListViewer), but I remember that the error with the index sometimes appeared in this project when it was 3 times less by the number of screens. That is, in simpler projects the error was, but it was much less common (on iOS 10.3 and 11.3). Approximately 1 time for 30-40 Live starts.

In a small simple test project, which I did recently

https://x.thunkable.com/projects/5b63f581f549bbd59ddc1d98/project/properties/designer/

I still could not find this error. Perhaps you just need to do more of this project to find it.

Note.

I met Thunkable for iOS around mid-April this year. And in one of my first projects I noticed the differences in indexing for the List block and the ListViewer component. When the first record was started in Live in the ListViewer, the index 1 corresponded, but the first record in the List block corresponded to the index 0. Then I thought it was very strange and inconvenient. And even made an amendment. But with the transition to X had to remove the amendment, since both of these objects began to be indexed from 1. Maybe the roots of the problem are somewhere here?

**Comment by AlexITMan** [comment] 2018-08-04 06:55
I found one of the very first projects when I occasionally met this error

 https://x.thunkable.com/projects/5b654cc9eda3fb421d7f729c/project/properties/designer/

**Comment by AlexITMan** [comment] 2018-08-04 07:34
But this is completely unpleasant.  After installing my project on the iPhone immediately received an incorrect index list.  It turns out that the problem is not with Live X, but with the Thunkable X engine?

**Comment by mark-friedman** [comment] 2018-08-04 19:58
@AlexITMan, for the project above that consistently exhibits the error, (i.e. https://x.thunkable.com/projects/5b62ee9338e652270d9c53a9/project/properties/designer/) what steps do I need to take when I run the app in order to see the error and how will the error show itself?

Also, thanks for letting us know that you see the error on a downloaded app in addition to in Thunkable Live.  That's very useful information!

**Comment by AlexITMan** [comment] 2018-08-05 07:57
Have you launched https://x.thunkable.com/projects/5b62ee9338e652270d9c53a9/project/properties/designer/ on iOS and this immediately causes an error in the form of a white screen?  It is interesting.  I have never experienced this.  Perhaps this is due to a lack of RAM.  I am now studying this issue.

 Try to run this version

https://x.thunkable.com/projects/5b5865df01f90009ea99f0b9/project/properties/designer/

To check the error using left drawer panel, go to the Lists screen.  If an error occurs, the screen will look like this

![default](https://user-images.githubusercontent.com/20015046/43683891-f27325f4-989d-11e8-882c-acdbc3e40c30.png)

**Comment by mark-friedman** [comment] 2018-08-06 17:11
I'm no longer seeing errors on any new copies of https://x.thunkable.com/projects/5b62ee9338e652270d9c53a9/project/properties/designer/, so I can't debug it.  I did see the error on a previous copy that I made on Saturday, but it fixed itself while debugging!  It appeared that the error was in the code generated by Blockly for the get-list-item block, rather than an error in the execution of the code.

I'm getting a bunch of errors in my browser console just trying to load https://x.thunkable.com/projects/5b5865df01f90009ea99f0b9/project/properties/designer/ and they prevent my making a copy that I can analyze.  I'm starting to think that maybe we're running up against the current 1MB limit on component+blocks+code size (perhaps in addition to the list index issue).  We've got a fix already in our code base for the 1MB limit, which hasn't been deployed to x.thunkable.com yet.  Let's see what happens once that is deployed (hopefully later this week).

**Comment by AlexITMan** [comment] 2018-08-07 05:32
Thank you Mark for your work!

I also drew attention to the limitation of 1MB.  Interestingly, Thunkable Live X for iOS works more reliably than for Android.  Under iOS, I saw only black squares and no image in the Image component when this limit is reached, and in the case of the Android app, it immediately crashes.

An error in the Blockly code when the index was received was in the original build from Google?  Do I need to report it to Blockly developers or do they know about it and fix it?  The thing is that I plan to do a short training course on Blockly in the near future and would not want to meet with this error again.

Mark, you wrote that in the nearest assembly the 1MB limitation will be removed.  Will there be a new restriction?  Can you somehow understand approximately how many components of blocks and program code can be created with this restriction?  The limitation of 1MB for me was about the level of creating 20 screens.

**Comment by mark-friedman** [comment] 2018-08-07 16:16
> Thank you Mark for your work!

You're welcome.

>I also drew attention to the limitation of 1MB. Interestingly, Thunkable Live X for iOS works more reliably than for Android. Under iOS, I saw only black squares and no image in the Image component when this limit is reached, and in the case of the Android app, it immediately crashes.

In general, it appears that the underlying React Native implementation for iOS has better error handling than Android.  We'll soon be upgrading to a new version of React Native and we hope that it improves things.

>An error in the Blockly code when the index was received was in the original build from Google? Do I need to report it to Blockly developers or do they know about it and fix it? The thing is that I plan to do a short training course on Blockly in the near future and would not want to meet with this error again.

I doubt that it is an error in Blockly itself, but with how we use it.  Unfortunately, we still don't quite now what exactly is causing the problem.

>Mark, you wrote that in the nearest assembly the 1MB limitation will be removed. Will there be a new restriction? 

The new restriction will be 100MB.

>Can you somehow understand approximately how many components of blocks and program code can be created with this restriction? The limitation of 1MB for me was about the level of creating 20 screens.

I don't have an estimate on how many components of blocks and program code can be created with the new restriction.  We're hoping that it is large enough that no one will ever create an app large enough to exceed the limitation!

**Comment by mark-friedman** [comment] 2018-08-07 16:17
Reopening, since we haven't figured out the root cause of the issue and it might therefore occur again.

**Comment by lisztomania1** [comment] 2018-10-16 03:38
Hello Mark and Alex,

I can confirm the bug in my project. I am relieved that you two have already done some work on that issue.

**It appears that the get...in-list -block sometimes uses 0 as first index and sometimes 1.**

My suspicion was already, that my **project has grown to be too large!** A solution for me and others could be to avoid large textstrings in the text-blocks.

Beneath that I identified that **the last selected Screen while compilation works fine and uses 1 as the first index of the list. All other Screens use 0 as first index** -> so at least this is consistent.

My public project is called local and I hope it will be a valuable contribution to the thunkable gallery (and to local shops for which it was made): https://x.thunkable.com/copy/da57f1a29f3ca1a5a530abef0503b3d6

Cheers,
John

**Comment by mark-friedman** [comment] 2018-10-16 22:17
@lisztomania1, can you provide a small, simple project that shows the `get...in-list__` block ever using 0 as the first index?  It is very difficult to track down bugs on a large project like yours.

Thanks in advance.

-Mark

**Comment by lisztomania1** [comment] 2018-10-17 16:13
Good morning @mark-friedman  and @AlexITMan ,

i hope today is a good day for chasing bugs.

I have extended my app with two more Screens which present the issue:
https://x.thunkable.com/copy/aea304c4adff83c82a29a05a982099a6


When you start the app, Screen 1 is okay. it behaves as it should.
The bottom contains a tab view (underneath the button for the navigation to the rest of the app)

Use the Tab navigator to go to Screen 2 and you will see that clicking on the listviewer behaves different from Screen 1.

Go from the Design Mode to the Block mode and try to understand the logic (it is really pure and simple).

Delete one or two gray blocks in Screen 2 to trigger new compilation. Now Screen 2 should be fine and Screen 1 should be corrupted.
By the way: its really annoying, that the live mode is always one step behind with compilation :-) .

Can you confirm the bug?

**Comment by lisztomania1** [comment] 2018-10-17 16:35
I provide you a project with nearly the same Screen1 and Screen 2 . It is a very small project and does not have this issue

https://x.thunkable.com/copy/4db58c990cc318b11395b5efadd8f0fe

**Comment by AlexITMan** [comment] 2018-10-17 18:05
Hi, 

unfortunately, I can not confirm your bug.  After the last update, on iOS for me some blocks related to the list stopped working altogether.  And the indexes from your example when I choose from the list I just do not appear in the Label.

The problem is that errors when working with a list, etc., appear only in very large projects.  Mark said that the limit on the size of blocks + resources + code (1 MB) will be removed, but so far I do not see it.  But I noticed that after the last update of the application under iOS, it began to work worse.  And it makes me very sad.

Alex.

**Comment by lisztomania1** [comment] 2018-10-17 18:08
Thx for your answer,

did you recognize that I shared two projects?

One is very large and one is very small. 

Did you check both of them?

**Comment by AlexITMan** [comment] 2018-10-18 06:05
Unfortunately, I can’t verify this, because some blocks on my iOS stopped working at all regardless of the size of the project.  I do not know when the developers will correct this situation with the blocks, so that I can look at your projects.

You can try to get the item by index using the "in list get sub-list from # to #" block and write, this block returns the correct item?

**Comment by AlexITMan** [comment] 2018-10-18 06:40
Interestingly, now my big project and your big project work with "in list get #" correctly.  Check it out again (update Live Thunkable)

**Comment by lisztomania1** [comment] 2018-10-19 03:08
Hi @AlexITMan and @mark-friedman,

my big project does NOT work correctly. I see no update in the appstore for thunkable Live

**Comment by lisztomania1** [comment] 2018-10-19 03:18
And the workaround with the get sublist from ... ist very smart but does not work for me (same problem)  Beneath that: bugchasing really sucks, without the man who has influence on the code making any statement on our input. That gives a bad feeling.

**Comment by mark-friedman** [comment] 2018-10-19 16:45
@lisztomania1 I'm pretty sure that the problem that you are citing isn't really related to large vs. small projects.  I believe that it is a another symptom of the live test companion being one step behind the blocks editor.  For example, in your "big" project I saw the problem initially but then I forced an update and everything worked just fine.

BTW, I've found that the easiest way to force an update is to just moving a top-level block a little bit in the workspace.  That causes no changes in the actual block structure but does force a new code generation.

We've really got to fix that "one behind" problem!

-Mark

**Comment by lisztomania1** [comment] 2018-10-19 18:41
Hi @mark-friedman ,

I really appreciate your help. The information to just move a top-level block is already extremely helpful!

**Comment by lisztomania1** [comment] 2018-10-20 02:41
Interestingly, the problem is not gone.

Moreover it seems that big projects are not the problem, but big screens may be. If my screen starts with functions and tab navigator, only the last compiled screen works correctly , the others have the get...in-list-problem :-( . Are you working on that?

**Comment by AlexITMan** [comment] 2018-10-21 15:06
I added small screen to my huge project on iOS 12.0.1, which was not related to lists, and again I saw a list indexing error.  In this case, even the block "in list get sub-list gave" an error!  You are right, problems with list in huge applications are not solved and the only way out is to make small projects with a small number of blocks.

**Comment by lisztomania1** [comment] 2018-10-22 18:09
Hi @mark-friedman,

the "one-step-behind" problem is one thing. 
The "get-in-list starts with 0 or 1 depending whether screen is chosen or not" is another. 
By the way the get substring from ... to ... has the same issue!

Do you have any progress on any of these two problems?

Hopefully,
John

**Comment by mark-friedman** [comment] 2018-10-25 20:45
We don't yet have a fix for the "one-step-behind" problem.  Until that's fixed, please jiggle a top-level block after any block changes to force an update to the Thunkable Live app.

For the "get-in-list starts with 0 or 1 depending ..." problem, in every case that I've seen of this it was actually fixed by jiggling a top-level block.  Please try and go through your projects where you see this error and jiggling a top-level block in each screen and let me know if that fixes things.  If not, please try again to create as simple as possible an app which demonstrates the problem and please share it here.

**Comment by AlexITMan** [comment] 2018-10-26 10:01
Hi @lisztomania1 

I think that temporarily it is better to use another crutch to eliminate the error of indexing the list.  On the list screen, I created another list with one item.  If this item is available at index 0, then the correction variable becomes equal to 1 and then subtracted from the index when the item is received.

By the way, does the "in list set #" block also work for you with an indexing error?  I cannot verify this, since my indexing error no longer manifested itself.

**Comment by lisztomania1** [comment] 2018-10-27 04:04
Hi @mark-friedman and @AlexITMan, 

I thank you both for working hard on these problems. It means alot to me!

The idea of @mark-friedman worked for me approximately 4-6 weeks ago in another large project of mine. Exactly as you said I went through all screens, made a slight change, and all screens one by one were corrected with each new compilation.
...But now (since circa 2 weeks) I am facing a different problem: Each time one Screen is corrected by change-triggered new compilation, all other screens become disarranged. Maybe this is a symptom of a further growth of my project. Maybe this is caused by a different arrangement of screens in tab and stack navigators ?!?

I already use the crutch with the variable, which I set to 0 or 1 depending on which screen I am working on (thx to @AlexITMan for bringing up this idea). I cannot say if the "in lists set ..." block has the error, beacuse recently other bugs like the "insert ... at last" + "for every j in list..." error are making my project totally scrambled and I try hard not to loose track of all the crutchs, that my project now depends on.

I sometimes really feel lost and ask myself if we (all guys with large projects) are just blocking resources of the thunkable team with our problems :-(

**Comment by lisztomania1** [comment] 2018-10-28 06:51
I am now fine with my workarounds. I use self-made procedures instead of the corrupted components.
https://community.thunkable.com/t/bug-on-thunkable-live-x-on-ios-block-in-list-get-returns-an-incorrect-index-in-a-large-project/40914/22?u=user81

What might be of interest for @mark-friedman, is that the "find-first-occurence-of-item-...-in-list..." gives back "-1" as output, If the item is not in the list. This is a logic result because it should be 0. 

-->> There is definitely a complete shift on every screen, which is not recently compiled. Hope this helps you finding the bug.

**Comment by lisztomania1** [comment] 2018-10-28 07:42
![image](https://user-images.githubusercontent.com/34504909/47613305-27eeb780-da8d-11e8-989c-f7a7fa5f7475.png)

this arrangement of component you see in the screenshot gives a really strange output:

the output of the join...-component is: "Variable j" + "" + "Variable j"  

- very strange!

**Comment by lisztomania1** [comment] 2018-10-28 07:46
...but that does not bother me anymore because I use my workaround functions:

![image](https://user-images.githubusercontent.com/34504909/47613348-d5fa6180-da8d-11e8-9120-ff2cd0cf49c3.png)

so my output of join...-component is: "Fitting emoji" + "" + "Variable j"

**Comment by AlexITMan** [comment] 2018-10-29 12:39
Hi, @lisztomania1 

I thought so.  The error of indexing the list affects not only one get # block and need to create own blocks to work with lists.  Thank you for experimenting and finding a solution to this huge problem.

**Comment by mark-friedman** [comment] 2019-07-13 00:39
This should be fixed in the latest release.  Please reload your project in the browser, try it out and let me know the result.

**Comment by mark-friedman** [comment] 2019-07-13 19:09
Actually, I just discovered that the fix that I thought had gone into yesterday's release did not get into that release, but should get into our next release early next week.  So sorry about the confusion :-(

**Comment by mark-friedman** [comment] 2019-07-22 19:13
The fix was released.  Note that you need to force a re-generation of the app code from your blocks by, for example, jiggling or changing a block.

**Closed by mark-friedman** 2019-07-22 19:13 UTC
