### ISSUE TITLE
Web designer goes to blank screen (white screen issue)

### ISSUE THREAD

**Issue by IanOstrom** [thunkable/thunkable-issues#247] opened 2019-09-11 14:21 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

X

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

Two students had the same issue when building an [image recognition app](https://youtu.be/3UWbWPlkjw8). 

### Steps to Reproduce
1. Seemed to happen suddenly when testing the app.
2. [Example](https://x.thunkable.com/projects/5d77d7d4f31828a6b00bd66f/openProject/designer)
3. 

### Expected Behavior
What did you expect to happen?

Thunkable editor loads normally in the browser.

### Actual Behavior
What actually happens?

Complete white screen except for the help chat button. Creating a new app works fine. Only the frozen app stays frozen when loaded in the editor.

```
  STACK TRACE AND/OR SCREENSHOTS

```
<img width="1440" alt="Screen Shot 2019-09-11 at 10 15 25 AM" src="https://user-images.githubusercontent.com/10860817/64705043-4418fe80-d47d-11e9-9f7b-8634b733b982.png">

**Comment by MrMazzone** [comment] 2019-09-11 14:48
I have also observed this behavior.  It seems to happen when you switch the size (width or height property value) of a component to a relative size (% of container) and leave in the previous value. To prevent this, clear the value before switching to a relative size. 

However, it would be nice to fix this bug. I am assuming the previous value is not compatible with the way the relative size works and needs to be cleared by the system when the user switches the type of size property.

**Comment by IanOstrom** [comment] 2019-09-12 00:48
Thanks Joe! I'll look out for that.

**Comment by tomer2526** [comment] 2019-09-17 06:00
To me, this happens when you move a block and delete it before you stop moving it

**Comment by mark-friedman** [comment] 2019-09-17 16:26
@MrMazzone 
Thanks, Joe.  That is repro scenario is very helpful!

-Mark

**Comment by mark-friedman** [comment] 2019-09-17 16:27
@tomer2526, How do you delete a block before you stop moving it?

**Comment by chickenpotpie123** [comment] 2020-06-21 23:55
This has happened to me twice now, the first time I just made a copy of the app and kept working, but the second time it happened later after adding a new screen, I went to try to go to the blocks tab from the design tab and it just went to that white screen... Now I can't enter the block screen on any of the screens I have in the app.

**Comment by jane-d-alt** [comment] 2021-01-08 17:58
Fixes can be written for when this behavior occurs in a reproducible way, as in the original report. If this issue occurs in your app, and it seems like a once-off (ie. cannot be reproduced), there may be an issue with your project. In this case, please contact the team. 

@chickenpotpie123 do you still have access to this project? If so, and if this issue wasn't resolved on another thread, could you share the link to this project?

**Comment by jane-d-alt** [comment] 2021-05-13 14:09
Hi again,
Since we haven't heard back from you, we will close this issue now. If you experience this behavior again, please reach out to support. Thanks!

**Closed by jane-d-alt** 2021-05-13 14:09 UTC
Labels: bug, moved
