### ISSUE TITLE
Issue with copying a project with Dataviewer & Airtable

### ISSUE THREAD

**Issue by vaskarni** [thunkable/thunkable-issues#748] opened 2020-11-19 20:12 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable X (Pro)
Windows 10 Home, Firefox

### Steps to Reproduce
1. Create a project with Airtable. Setup a Dataviewer and link with Airtable. Create a List. Works fine.
2. Copy the project to a new one. Open this project - Dataviewer does not work. 
3. The list shows default Thunkable list (image attached).

### Project Link
Easily reproducible. Link to project can be provided if needed. 

### Expected Behavior
Expected the Dataviewer to work as in the original project.

### Actual Behavior
Dataviewer stops working. In one case it messed up the Data Sources when I tried to fix it and even the original project stopped working. I had to delete Data Sources and recreate to make it work.
![DataviewerCopyIssue-1](https://user-images.githubusercontent.com/60406446/99718804-4eab2c80-2a60-11eb-845c-24149fe729f8.JPG)

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment] 2020-11-19 20:36
Hi there, this is by design, as you can make copies and send them to others and you wouldn't want to share your API keys.

There is a discussion [here](https://github.com/thunkable/thunkable-issues/issues/654) about changing this behaviour for local copies, but for now this is still the intended design.

Closing as a Duplicate of #654 please follow the conversation there.

**Closed by josmas** 2020-11-19 20:36 UTC
