### ISSUE TITLE
First click on the screen when keyboard is open

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#540] opened 2020-05-24 18:32 UTC
### Platform: Thunkable X - all versions

This is my mystery of the day: my app has several screens that behave in two different ways.
Imagine that you have the focus on an input field that you have just filled in, and the keyboard is still visible. Now click on a button.
1) On some screens the click starts the commands procedure provided by that button while the keyboard remains open, visible (which also annoys).
2) On other screens, the click produces the only effect of closing the keyboard (and the touch could be done anywhere on the screen, obtaining the same result); but in this case it is necessary to press the button again to continue.
In the first case, it is possible to use the "dismiss keyboard" block of the device drawer (as first instruction of the button) to resolve the issue.
In the second case, I don't know what to do. Can someone help me?
But, above all, can someone explain to me why apparently identical screens behave differently?Thanks

**Comment by domhnallohanlon** [comment] 2021-02-12 14:27
Hi @Bellacopia, 

I've created a sample project which _I think_ replicates the scenario you are describing, however I can't reproduce the behaviour that you describe above. 

https://x.thunkable.com/projectPage/60268e01cd3cec42e47b6a31

Would you mind taking a look and let me know what you think? 

Thanks!

**Comment by domhnallohanlon** [comment] 2021-04-16 13:56
Hoping this is working for you as well @Bellacopia.

Closing this issue for now, but feel free to open a new one if it happens again.

Thanks, 
Domhnall

**Closed by domhnallohanlon** 2021-04-16 13:56 UTC
