### ISSUE TITLE
Bug with make copy function (with Thunkable X)

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#578] opened 2020-06-30 11:07 UTC
Dear Thunkable Team,

Since yesterday I've encountered a strange bug with Thunkable X. Namely, when I make a copy of a project when within the project, the date of the copy is wrong. The copy is dated a few months ago, which might coincide with the date when I started the whole project (don't remember) but in any case the date is off. However, when I make a copy in the overview window (the overview listing of all my projects), it works well. I wonder what causes this strange behavior, but hope you could get it fixed. Not a big problem but with multiple projects and copies (i.e. versions) this causes some confusion, as I usually like making copies while I working on the project. Before yesterday it worked well.

Thank you! Keep up the good work!

Heikki

**Comment by josmas** [comment] 2020-06-30 11:22
@Heikkiss thanks for your report.

Could we have a few more details? I cannot reproduce following your description. If I am in card mode and duplicate a project, it goes to the top. If I am inside a project and click 'Make copy' and then go back to the list, I also see it on top of the list. Is this not happening to you?

**Comment by Heikkiss** [comment] 2020-06-30 11:33
Hi @josmas -- oh I just realized what the problem was. Namely, when I exited the project and went back to the project listing, there it gave me a wrong date for the copy. However, when I refreshed -- after a while -- the listing page, the date was right. I've been using Google Chrome. But perhaps the main, underlying problem was that I've been working with a reduced Interned speed for the past days so that a genuine refreshing of the listing took a while. So I guess it's problem solved then. Thank you! And sorry for raising the issue perhaps too fast, it was just bugging me yesterday and noticed it again today.

Best, Heikki

**Comment by josmas** [comment] 2020-06-30 11:37
Heya, yeah, that would make sense, we refresh the page automatically but it might take a while, especially on slow connections. Not a problem in any case, thanks for letting us know. I'll close this for now, feel free to reopen if needed at some point. Thanks!

**Closed by josmas** 2020-06-30 11:37 UTC

**Comment by Heikkiss** [comment] 2020-06-30 11:39
Thanks @josmas ! Best, Heikki
