### ISSUE TITLE
Status bar bug

### ISSUE THREAD

**Issue by Irwin2004** [thunkable/thunkable-issues#779] opened 2020-12-17 03:47 UTC
### Platform
Thunkable Live version 248

### Issue/Request Origin
![image](https://user-images.githubusercontent.com/73010436/102440946-2cef9600-405c-11eb-8a6a-66377180ec8d.png)
I've change my status bar into white color (before dark blue).

![Screenshot_20201217-113845_1_1](https://user-images.githubusercontent.com/73010436/102441372-17c73700-405d-11eb-8fb0-8010676def6f.jpg)
When I download the application and see in thunkable live application, why the status bar still dark blue?

### Step to Reproduce
1. Open Thunkable Live
2. The status bar have dark blue color

### Expected Behavior
The status bar will have white color

### Actual Behavior
The status bar have dark blue color

**Comment by josmas** [comment] 2020-12-18 13:50
Hi @Irwin2004 if you download the app and install on your device, is the bar blue or white?

**Comment by Irwin2004** [comment] 2020-12-18 14:09
Hi @josmas, thank you for your respond. The status bar is blue.

**Comment by josmas** [comment] 2020-12-18 15:51
Hi @Irwin2004 I just tried on latest build and I cannot reproduce. If I set the bar to white and the style to dark, I see a white bar with darker icons. Is there anything different or specific you are doing in your app? Note that this setting is specific for each screen.

If you can send a copy link to a project that reproduces this issue, that would be much appreciated. Note this should be the simplest project that reproduces the issue; one screen tops. Thanks!

**Comment by Irwin2004** [comment] 2020-12-18 16:58
Hi @josmas, the problem is status bar color of tab navigator (sorry I forget to tell you that I use tab navigator). The status bar color is still blue.

If the screen (outside of tab navigator), the status bar already white. But the icons don't change to dark. This problem happens to my splash screen too.

**Comment by josmas** [comment] 2020-12-18 18:31
Hi there, can you clarify if this is one issue or two?

Outside of a navigator, does it work as you expect or is there an issue with icons not showing?  If you have a white background you should choose the dark style.

Within the navigator, I can see that the color seems to be reset. So this is problem number 1, but please clarify if there is a problem number 2 with the bar style. Thanks!

**Comment by Irwin2004** [comment] 2020-12-19 01:11
Hi @josmas, actually there was 2 issue, but the first issue already fix (outside of tab navigator). The second issue is the status of the tab navigator.

**Comment by josmas** [comment] 2020-12-19 01:17
alright, thanks for the update. We'll look into the navigator issue. Thanks!

**Comment by josmas** [comment] 2020-12-21 16:17
hey @Irwin2004 can you try something for me? I found that if I set the colour for all of the tabs in the navigator to white, then they do stay white. Could you try that? It seems like the last one will override the values for the other ones. If you could please confirm that is what you see; thanks!

**Comment by josmas** [comment] 2021-01-05 17:38
We have a fix for this; will be deployed in the next few days (once approved at stores). Thanks.

**Closed** 2021-01-15 06:57 UTC
Labels: bug, moved, planned work, question
