### ISSUE TITLE
Web Viewer URL does not update

### ISSUE THREAD

**Issue by Antoriccio9** [thunkable/thunkable-issues#444] opened 2020-03-31 13:29 UTC
Hi everybody, 
I'm trying to build an app that displays two web pages ( in the upper and lower half of the screen ) and that has to check if these pages are equal while the user navigates.

I’m trying to use two web viewers ( as in the picture), but the URL variable is not dynamically updated.

For example, let's say I open on the upper Web Viewer the Google main page and on the lower one the Apple web page.
The URL variables will be https:www.google.com for the upper one and www.apple.com for the lower one.

Once the pages are loaded I search on Google( Upper WV) the apple web site, now the URL variables should be the same but the upper one remains: www.google.com even if the Web viewer is showing the Apple website.

I saw that this issue was brought up by different users on the thinkable community.

Is it feasible to fix it your opinion?

Thank you so much, 
I really appreciate your work
<img width="318" alt="Screenshot 2020-03-31 at 12 33 12" src="https://user-images.githubusercontent.com/62944705/78031677-29986b00-7364-11ea-8426-b2e477a7efa5.png">

**Comment by josmas** [comment] 2020-03-31 13:36
Hi there, can you please link to a project copy so we can reproduce on our side?
A link and step by step instructions of what you do and what you expect to happen would be helpful. Thanks!

**Comment by Antoriccio9** [comment] 2020-03-31 13:46
Thank you for the fast answer, ,
should i attache the link  and the step by step info here or in the Git Hub post??



Kindly,
Antonio Vinciguerra

**Comment by josmas** [comment] 2020-03-31 13:48
Heya, not sure what the github post is?

Is it that you received the answer as an email? If so, you can either reply to the email, or reply in this thread (which I guess is it the github post). Either way it will end up in the issue you opened. Hope that clarifies!

**Comment by Antoriccio9** [comment] 2020-03-31 15:22
Thank you so much Josmas, here is the link to the Project: https://x.thunkable.com/projects/5e835178f76b3380c3cb415d/47421d66-69b5-42a9-8016-df2d892efd8d/designer <https://x.thunkable.com/projects/5e835178f76b3380c3cb415d/47421d66-69b5-42a9-8016-df2d892efd8d/designer>

You’ll find a mono screen app divided in two as i described in the original thread.


If you paste the same URL in both the text inputs and set them, when you press check the app recognises that you are looking at the same page. ( showing a message : Same Page ! ) 
and if the two INITIAL url are different, after pressing check, it shows the message :  Different Page!

( if you press the button “set” again the label on its right will show the url that the app is reading )

Up to now everything works, the problem arises when i navigate into the browsers.

If you paste the  Google url on  the upper tex input and on the lower one the Apple web page url,  the URL variables will be https:www.google.com <http://www.google.com/> for the upper one and www.apple.com <http://www.apple.com/> for the lower one. 

Once the pages are loaded  if you search on Google  for the apple web site,  the URL variables should be the same but the upper one remains: www.google.com <http://www.google.com/> even if the Web viewer is showing the Apple website.

Therefore the app recognises that i’m on the same page only if i’m pasting the same url at the beginning, not if i navigate into the pages.




i’m available For any other clarifications 


Kindly,
Antonio Vinciguerra

antonio.viciguerra@mail.polimi.it

**Comment by Antoriccio9** [comment] 2020-04-14 18:21
Hey, I managed to do what I was trying to do on Thunkable in MIT app inventor, there the web viewer feature updates the URL when it changes. Any clues of when this will be possible also on thunkable?

**Comment by josmas** [comment] 2020-04-15 16:24
Hey @Antoriccio9 so you basically would like a `get current URL` block as in https://github.com/thunkable/thunkable-issues/issues/461 by @MrMazzone ? Would that solve your issue?

**Comment by Antoriccio9** [comment] 2020-04-15 16:33
Hi Josmas!

I’ve already tried a similar block in MIT App Inventor as Mr Mazzone did  and it works….. so yes, a block like the one that you described is exactly what i’m looking for.

How long do you think it will take to have it available on Thunkable X ? 


Thank you so much for your help!

**Comment by josmas** [comment] 2020-04-15 18:04
Hi @Antoriccio9 there are a few things that we would need to add to make it work like App Inventor; I will add it as a request but we don't have an ETA at the moment. Thanks!

**Comment by josmas** [comment] 2020-04-15 18:08
We are going to consolidate the requests, so closing this:
Duplicate of #461 

Thanks for the request!

**Closed by josmas** 2020-04-15 18:08 UTC
Labels: enhancement, question, to be considered (no ETA)
