### ISSUE TITLE
Screen Error when typing

### ISSUE THREAD

**Issue by orderrex** [thunkable/thunkable-issues#255] opened 2019-09-17 17:43 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X
### Issue/Request Origin
staff

### Steps to Reproduce
1.search
2. tyype in keyboard
3.screen size changes

### Expected Behavior
What did you expect to happen?
normal full screen
### Actual Behavior
What actually happens?
```the screen size changed automatically as i started typing using the keyboard
  STACK TRACE AND/OR SCREENSHOTS
```
![WhatsApp Image 2019-09-17 at 10 53 38](https://user-images.githubusercontent.com/55457819/65065796-06cfd780-d97b-11e9-922e-dec1853d0baa.jpeg)
![WhatsApp Image 2019-09-17 at 10 53 37](https://user-images.githubusercontent.com/55457819/65065807-0b948b80-d97b-11e9-976b-b13c2e42214f.jpeg)

**Comment by mark-friedman** [comment] 2019-09-17 20:12
@orderrex , The behavior of compressing the screen when the on-screen keyboard is active is by design.  If I am misunderstanding the issue that you are describing, please let me know.

**Comment by orderrex** [comment] 2019-09-17 20:16
i do not think this is by design. the screen size changes even after the keyboard has gone.

**Comment by orderrex** [comment] 2019-09-17 20:18
i do not think this is by design. the screen size changes even after the keyboard has gone. @mark-friedman

**Comment by mark-friedman** [comment] 2019-09-17 20:19
@orderrex Thanks for the clarification.  Can you post a copy/share link to your project, or better yet an even simpler project that demonstrates the issue?

**Comment by orderrex** [comment] 2019-09-17 20:21
@mark-friedman https://x.thunkable.com/projects/5d763259299f0869fdfbc057/204a36be-7973-44ac-a52c-3463f408fe0b/designer

**Comment by orderrex** [comment] 2019-09-17 20:36
@mark-friedman i have added a button so that you can see the ordering menu, please click on this then add an item to the basket and type a comment you see the problem

**Comment by mark-friedman** [comment] 2019-09-17 22:30
@orderrex Interestingly, this appears to be an iOS-only problem and related to the interaction between keyboard input and the Web Viewer.  This might take a while to diagnose and to fix.  

Just so you know, in general we don't encourage apps which simply wrap an existing web site, especially if the web site has extensive interactive behavior.  It's not always easy to maintain fidelity with the original web site and it somewhat moots the point of using Thunkable in the first place.

**Comment by jane-d-alt** [comment] 2021-01-08 17:55
This behavior has been resolved. We will now close this issue. Apologies for not following up when this behavior was originally resolved.

**Closed by jane-d-alt** 2021-01-08 17:55 UTC
