### ISSUE TITLE
Empty padding at the bottom of screens

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#457] opened 2020-04-05 19:36 UTC
### Platform
✕ Android, ✕ Android companion

### Steps to Reproduce
On the X Android companion: Preview any project, even ones that have not been edited in ages
On the X Android: Any apps compiled after (approximately) Saturday, April 4th 2020

### Expected Behavior
There should not be any white gaps in the bottom of the app screens

### Actual Behavior
There is a white gap on the bottom of the app's screen

### Screenshots
Plenty of them, here: https://community.thunkable.com/t/problem-live-test-onandroid-screen-empty-padding-at-the-bottom/552876

**Comment by MrMazzone** [comment] 2020-04-05 19:52
I can confirm this behavior.  Seeing it on my end.

**Comment by kezb765** [comment] 2020-04-06 13:11
I have the same problem, when enabling "scrollable" for a column (setting "scrollable" for the whole screen is not always an option).

**Comment by josmas** [comment] 2020-04-06 17:54
Thanks all for the report and confirmation. We are testing a number of changes on columns; we'll get back to you as soon as we know more. Thanks!

**Comment by AmigoDeluxe** [comment] 2020-04-07 17:34
@josmas out of curiosity, did anything change in the backend? If not, how would you explain this change impacting everybody?

**Comment by josmas** [comment] 2020-04-07 19:54
hi @AmigoDeluxe this looks like a library upgrade and the style tag behaving slightly different in the newer version. The change would most likely have happened on the Companion itself, and those changes in UI rendering trickle down to compiled apps. We are still trying to figure it out though, so take that with a pinch of salt! :)

**Comment by hencehuman** [comment] 2020-04-09 00:01
Thought it was just me... how's it coming along?

**Comment by grfr58** [comment] 2020-04-09 17:49
I found a tournaround for this problem. On the screen set the bottom margin first as negative number example -30 and test the app and then you can try to set to 0.
For me it fix the problem. I think is a missing default value on the library

**Comment by hencehuman** [comment] 2020-04-09 17:51
Damn, I love this fix already. Thank you. Will try.

**Comment by AmigoDeluxe** [comment] 2020-04-09 18:08
What library?

**Comment by AmigoDeluxe** [comment] 2020-04-09 18:28
So, setting the screen's bottom margin to -30, viewing the app in the companion, then setting it to 0 and viewing the app in the companion does not solve the issue.

**Comment by hencehuman** [comment] 2020-04-10 03:31
I just tested and it seems to be working in the companion for one of my
android devices and not the other. However, the built app works for both of
them. Thank you for this fix!

**Comment by hencehuman** [comment] 2020-04-10 04:04
Just noticed the statusbar was showing in my app although it wasn't enabled
in the screen settings. Toggling on and then off again fixed it. Not sure
it was related to the -30 padding fix but it happened after that. Yes, I
wrote padding, not margin... apparently, I read padding instead of margin
in the previous thread posts and did it that way instead... and it worked.
I just tested and it seems to be working in the companion for one of my
android devices and not the other. However, the built app works for both of
them. Thank you for this fix!

**Comment by grfr58** [comment] 2020-04-10 08:00
According to me there are other parameter without default setting like the 
show status bar or even the orientation of the screen.

In data 10 aprile 2020 05:05:06 hencehuman <notifications@github.com> ha 
scritto:
>
> Just noticed the statusbar was showing in my app although it wasn't enabled
> in the screen settings. Toggling on and then off again fixed it. Not sure
> it was related to the -30 padding fix but it happened after that. Yes, I
> wrote padding, not margin... apparently, I read padding instead of margin
> in the previous thread posts and did it that way instead... and it worked.
> I just tested and it seems to be working in the companion for one of my
> android devices and not the other. However, the built app works for both of
> them. Thank you for this fix!
>

**Comment by josmas** [comment] 2020-04-10 11:40
All, there is an update that should fix some of the padding issues. Let us know if that is not the case. But please note that this needs a new Companion app and we are waiting  for Apple to approve the latest build, so it might take a while to show up.

**Comment by josmas** [comment] 2020-04-10 11:42
@AmigoDeluxe this was a combination of and upgrade to react native 0.61 and us having a constant height for the status bar.

**Comment by AmigoDeluxe** [comment] 2020-04-11 12:32
Just installed Thunkable Companion version 175 on my device but I am not seeing any improvement on this issue. I tried refreshing my project, deleting the app's cached data, tried again, no love. The app's screen is shifted downwards creating white gap at the top and hiding its very bottom. @josmas is this the version we should be expecting or is there another on its way?

Thanks
K

**Comment by grfr58** [comment] 2020-04-11 12:52
Did you tried to set the bottom margin of the screen at -30 ?

In data 11 aprile 2020 13:32:20 AmigoDeluxe <notifications@github.com> ha 
scritto:

**Comment by AmigoDeluxe** [comment] 2020-04-11 13:03
Not with version 175 of the Companion. I would rather wait for a proper fix.

**Comment by josmas** [comment] 2020-04-11 13:25
@AmigoDeluxe yes, 175 should contain a fix for column padding. Is this happening in more cases than columns? If anyone can link to a minimal project with the issue, especially if it is nor column related, I can try and reproduce again.

**Comment by AmigoDeluxe** [comment] 2020-04-11 14:08
**Update**: I set all my project's screens margins and paddings to 0 for all four sides and interestingly enough, that fixed the top white space however, the bottom of the screen is still off. And then, all by accident, **I tilted my device to landscape and... ta daaaaa**!!! The very bottom of the screen is now visible... So there seems to be something specific to portrait mode. If you wonder what that is... it is the bottom navigation bar which is not visible on landscape mode.

I then tilted my device back to portrait mode and got the known issue of the companion showing the contents of the app screen up to the middle of the screen and... guess what? I can now see the bottom elements of my app's screen! 

So now it is very clear what is happening. The app's screen goes all the way from top to the bottom but behind the navigation buttons as if they are in "always-on-top" mode.

@josmas does this help at all?

Thanks
K

**Comment by AmigoDeluxe** [comment] 2020-04-11 14:23
Oh... and one more thing... if you create a new project with a new screen, set its vertical alignment to top and create a label in it you will see that the label will go straight to the top, without needing to set the screen's paddings and margins to 0 like you now have to do with previously existing apps. This means that the apps we have created up to about a week ago need to have their margin properties set to 0 as previously mentioned by others in this thread. This could be a clear sign of our projects "breaking" because of the React library update but should the Thunable developers know about this, they should find a way to update our projects in batch rather than hoping that we notice what is going on and having to manually update them. Change management and communication has been a problem with Thunkable but I hope it will be solved in the near future. Thunkable needs to understand that some of us are making money by apps we build on this platform and that we can get in real trouble if we push an updated version which break functionality without us knowing until it is too late.

**Comment by AmigoDeluxe** [comment] 2020-04-15 16:03
@josmas, would you like any additional information on this issue? What do you think about the above mentioned?

Thanks

**Comment by josmas** [comment] 2020-04-15 16:17
@AmigoDeluxe thanks a million for the extra info, that should be enough to track this down but unfortunately I haven't had a chance to look into it. Hoping to have some time towards the end of the week, but that is all very helpful!

**Comment by josmas** [comment] 2020-04-21 11:34
FYI: We are still looking into this. Unfortunately it seems to have more edge cases than we anticipated.

**Comment by balancedkitchen** [comment] 2020-04-24 18:08
I have the same problem!

**Comment by AmigoDeluxe** [comment] 2020-04-25 12:02
@josmas imagine how inconvenient this is for tens of developers who actually earn their living by applications they built. How is the troubleshooting progressing? Feel free to find us on Discord (https://discord.gg/wgRCzA8) and discuss about the issue if you need help.

**Comment by balancedkitchen** [comment] 2020-04-26 07:05
Please, Thuncable support with information on when this issue is expected to be resolved. My paid subscription time is running and I can't use the platform. Be so kind as to commit yourself to some time to resolve it.

**Comment by josmas** [comment] 2020-04-27 15:57
All, we are trying to catch all the cases in here. Some users reported this being fixed a couple of weeks ago, but what seemed to be a padding issue, it is now a complicated series of cases involving the status bar and the various navigation components, alongside combinations of scrolling settings and outstanding issues with screen orientation (which currently are only supported on iOS, whilst this issue seems to be reported for Android).

If you have links to minimal public apps that reproduce certain cases please do share copy links.

**Comment by balancedkitchen** [comment] 2020-04-27 16:14
Strange! I have a problem with Android and iOS.
https://x.thunkable.com/copy/2225f0e078a91486357b35e603483adb
screen: StoreScr
hope to help resolve it quickly. It's been a long time!

**Comment by josmas** [comment] 2020-04-27 16:36
Hi @balancedkitchen thanks for the link but we really need a minimal app. I don't know if the issue shows before or after registering on your app, as your background is white at least for the first couple of screens.
Thanks in any case.

I can reproduce some cases of whitespace at the bottom with a bottom navigator, and they all seem to be related to the lack of support for screen orientation. Unfortunately we set the default orientation as `auto` which is not supported on Android. By locking all screens to `portrait`, the issue seems to go away. Can any of you try that?
This is obviously only a quick workaround and we will fix the orientation issues on both platforms, but if you can try locking to portrait (property is at the bottom of the screen properties panel) and let us know, that would help a lot!

**Comment by balancedkitchen** [comment] 2020-04-27 17:44
This app worked flawlessly before your platform update.

**Comment by AmigoDeluxe** [comment] 2020-04-27 18:29
@josmas one thing is for sure. The status bar is now transparent and that is not something everyone would want. Before the latest update, the status bar was not transparent so if this has now changed, that's great news however, it should be an option which could look like this:

![image](https://user-images.githubusercontent.com/7762893/80407265-09f65300-88ce-11ea-96d8-9bfc01d3ff71.png)

I hope this makes sense. Again, feel free to join us on Discord and discuss: https://discord.gg/wgRCzA8

Thanks
K

**Comment by josmas** [comment] 2020-04-27 21:43
The status bar has not been changed and I don't see it as transparent. What exactly do you mean?

Does any of this happen if you are not using a navigator?
I can reproduce some cases of the status bar not being properly hidden/revealed when changing from different tabs in a navigator. 

I can also see the space at the top while on the companion, but not when I download the Android app.

**Comment by AmigoDeluxe** [comment] 2020-04-28 06:58
@josmas you need to compile the app. You won't see this bug in the Companion. Here are screenshots showing the issue on 3 different devices:

![Samsung Galaxy S10](https://user-images.githubusercontent.com/7762893/80456408-32b23300-8936-11ea-8b62-68e24da88974.jpg)
![Huawei P smart Z](https://user-images.githubusercontent.com/7762893/80456414-35ad2380-8936-11ea-8b62-3340cee38cca.jpg)
![Honor 9 Lite](https://user-images.githubusercontent.com/7762893/80456418-36de5080-8936-11ea-87ca-1ec9cdc7a661.jpg)

The screen now goes **BEHIND** the status bar while before the update the topmost of the app's screen would be the first line **BELOW** the status bar, not **BEHIND** it. 

K

**Comment by balancedkitchen** [comment] 2020-04-28 09:38
Here is my problem
![Screenshot_2020-04-28-12-23-41](https://user-images.githubusercontent.com/46844220/80472053-e45c5e80-894c-11ea-8890-c361e57ec0e1.png)
![Screenshot_2020-04-28-12-29-56](https://user-images.githubusercontent.com/46844220/80472060-e6262200-894c-11ea-9819-a803aa476a0a.png)
![Screenshot_2020-04-28-12-29-25](https://user-images.githubusercontent.com/46844220/80472065-e8887c00-894c-11ea-8127-68e6df1838a7.png)

Link to a simple application.
https://x.thunkable.com/copy/8366dd8e41b2709f4df9949c7d05bdab

**Comment by josmas** [comment] 2020-04-28 14:10
@balancedkitchen thanks for the link but I don't really know what to look for in there. It is mostly an empty page with a loading icon. Do I have to click anywhere to see the issues?

**Comment by josmas** [comment] 2020-04-28 14:13
@AmigoDeluxe I don't see a transparent statusbar in compiled apps. That can be because there are a number of factors like scrolling, use of columns/rows or navigator elements and so forth. This is why we ask for the simplest app that reproduces the issue. That is an app with the minimum number of elements. We generally get app links with 10s of screens and hundreds of components and blocks, and we can do little with that. There are too many combinations.

**Comment by balancedkitchen** [comment] 2020-04-28 14:17
Yes. Pictures are buttons that make invisible one column and visible another. Note that the columns that should be visible do not fill the entire screen.

**Comment by josmas** [comment] 2020-04-28 14:21
@balancedkitchen I cannot click on anything on Android Companion. I see the loading icon and a shopping trolley at the top right, but cannot click either. The rest is white.

**Comment by AmigoDeluxe** [comment] 2020-04-28 15:02
@josmas here is an minimal app as requested: https://x.thunkable.com/copy/2b6df0c50d810ce65b7a4e17a06908aa

Use the drawer navigator to switch between screens. Each has its own settings and the issue occurs in every single scenario:

**- Screen-NoScroll-Portrait**: The background image is set on screen level which is set to not scroll and the orientation is locked to Portrait.
**- Screen-Scroll-Portrai**t: The background image is set on screen level which is set to scroll and the orientation is locked to Portrait. I had to add at least one label to make the image appear as the screen height would otherwise be zero.
**- Column-ScreenNoScroll-Portrait**: The background image is set on column level, the screen is set to not scroll and the orientation is locked to Portrait.
**- Column-ScreenScroll-Portrait**: The background image is set on column level, the screen is set to scroll and the orientation is locked to Portrait. I had to add at least one label to make the image appear as the screen and column height would otherwise be zero.
**- Scree-NoScroll-Auto**: Just like the fist screen but setting orientation to Auto, just to be sure whether that plays a role or not.

Feel free to remix and experiment.

K

**Comment by josmas** [comment] 2020-04-28 15:31
Thanks @AmigoDeluxe I can see the transparent bar now. I need to track down when that was changed; I can really not see it in our source changes. I'll keep working on it in any case.

**Comment by AmigoDeluxe** [comment] 2020-04-28 15:52
Thank you @josmas . I am no coder but it only makes sense to see how you are implementing the following after your upgrade to [React 0.61](https://reactnative.dev/docs/0.61/statusbar#translucent):

_**translucent**
If the status bar is translucent. When translucent is set to true, the app will draw under the status bar. This is useful when using a semi transparent status bar color._

Interestingly enough, this property was not introduced in 0.61 but is around since version 0.5 back in 2015. We know that you upgraded to React 0.61 but maybe that was not only thing that got updated about 2 weeks ago so please check with your team internally.

I **really** hope this helps
Konstantinos

**Comment by balancedkitchen** [comment] 2020-04-28 16:17
> @balancedkitchen Не мога да щракна върху нищо на Android Companion. Виждам иконата за зареждане и количка за пазаруване в горния десен ъгъл, но не мога да щракнете и върху двете. Останалото е бяло.

I'm tired! Look at the photos! If you think this is normal and is caused by my ignorance. OK. For me, this topic is closed . I'm totally done with Thunkable.

**Comment by josmas** [comment] 2020-04-28 17:46
Hi @AmigoDeluxe the thing is that we are not. We do not use `color` or `translucent` because they are Android properties only and we want options to be as seamless as possible for both platforms. As we are not setting translucent, the default value is false, so that's why I cannot find why the bar goes translucent even if we are not setting it in any way. That is the debugging I am trying to do at the moment. It is possibly override by some other value, but we need to find out what is causing it. Thanks for your help!

**Comment by AmigoDeluxe** [comment] 2020-04-28 18:20
My pleasure @josmas . Feel free to use me as a guinea pig, I am more than happy to help. Here is something I found which may be relevant as it was last updated... (wadayaknow?) 14 days ago! If apart from React you also updated to Expo SDK 37, this could be it:

_"As of SDK37 being out for a while and StatusBar API being fixed in this release"_
https://github.com/expo/expo/issues/2813

I hope it helps.
K

**Comment by hencehuman** [comment] 2020-04-28 18:20
How are paid users being compensated for this since it's causing problems
and delays for us?

**Comment by AmigoDeluxe** [comment] 2020-04-28 18:25
@hencehuman let's focus on what is important for now. We will come to that later. Stay classy.

**Comment by hencehuman** [comment] 2020-04-28 18:27
Thanks for responding.

**Comment by josmas** [comment] 2020-04-28 19:38
hey @AmigoDeluxe yeah, thanks for the info. We have only just started migrating to v37 because even though it's been out for a couple of weeks, their development branch has been very busy with fixes and we prefer to upgrade when things get patched up a little. There are a number of fixes that we hope to get from the update, but merging takes a while because we use a lot of stuff outside of expo, so not everything is compatible all the time. I believe that the current issues we are seeing are related to screen orientation changes we made in the last update though, but still debugging through the code as I cannot find where things are going wrong.

@hencehuman if you have any issues or questions about payments please contact support through intercom.

**Comment by AmigoDeluxe** [comment] 2020-04-28 19:42
Thanks @josmas .

**Comment by AmigoDeluxe** [comment] 2020-04-30 19:47
@josmas I tried to understand under which conditions the issue bottom blank space occurs and tried all combinations involving the scrolling option for a screen which contains a column in the typical scenario we used to follow to get a screen scrolling (setting the screen to not scroll and creating a column which would scroll, then place everything in the column). Here is what I found:

1. Screen scroll, column scroll: No blank space but scrolling does not always work 
2. Screen scroll, column no-scroll: No blank space. This is actually the only scenario that works without issues
3. Screen no-scroll, column scroll: Issue... there is a blank space at the bottom of the column. See below for a short analysis...
4. Screen no-scroll, column no-scroll: No issue but... the screen won't scroll in this case so not really an option...

In all scenarios the column height is set to "Fit contents" as it should and the screen vertical alignment is set to Top.

Regarding scenario 3, it is worth noting that after doing some testing, it is the column that has the white blank space in its bottom, not the screen. I think this is where you should focus your investigation. Just a thought...

I will now check if scenario 3 works ok on iOS and report back. 

Cheers!

**Comment by AmigoDeluxe** [comment] 2020-04-30 22:21
@josmas so on iOS there was another issue; the bottom of the screen was cut by a few pixels, equal to the height of the status bar so, having had enough with this, I completely disabled the status bar on all screens of my app, republished on both iOS and Android and at least now I have something that I can looks ok (minus the status bar). I am available if you need further testing.

**Comment by AmigoDeluxe** [comment] 2020-05-01 07:32
@josmas looks like I spoke too fast. Disabling the status bar does not help on iOS with the issue mentioned in my previous post. I would expect that the status bar would be completely removed and allow the top of the app to be at the top of the screen. Instead, the information displayed on the status bar is gone but the space it occupies on the screen is still there. 

I guess that for now, the only option is to re-enable the status bar as it looks silly to have an empty stripe on the top of the screen, and then add some padding at the bottom of every screen (or column, will see) to fix the issue with the bottom-most of the screen not being fully visible. 

Perhaps some more information to help towards resolving this.

**Comment by AmigoDeluxe** [comment] 2020-05-01 12:54
Added 25 pixels padding at the bottom of every container. Looks almost as before the issue occurred. Looking forward to a permanent fix.

**Comment by AmigoDeluxe** [comment] 2020-05-04 16:16
Hello! Almost a month has passed since the bug was opened. Any updates? Thanks

**Comment by jaredgib** [comment] 2020-05-04 16:26
Following this. My users just noted this to me which means not only the Thunkable developers notice anymore.

**Comment by balancedkitchen** [comment] 2020-05-04 17:48
Anyone who wants compensation or a refund to write to this email: billing@thunkable.com. If you are lucky, someone can reply.

**Comment by jaredgib** [comment] 2020-05-04 20:20
> Anyone who wants compensation or a refund to write to this email: [billing@thunkable.com](mailto:billing@thunkable.com). If you are lucky, someone can reply.

Probably not looking for a refund. But would love to hear about any updates or potential updates in the works for these.

**Comment by josmas** [comment] 2020-05-05 02:18
Hi all,

as mentioned before, this seems to be a number of related issues. We will soon provide more options for the style bar (there are a number of requests about this) and we are tracking down all the spacing issues (we have refreshed row and column components), as well as moving to version 37 (this will take a bit longer, but it seems to be a lot more stable with regards to the status bar, as noted in a thread above). The first couple of changes will be visible to test users by the end of the week, and if all goes well and all is actually fixed, we will release to all after that. Thanks all for your patience with this.

**Comment by josmas** [comment] 2020-05-05 15:14
heyy @AmigoDeluxe I am trying to replicate case 3 above: This is a project with the things you note there `Screen no-scroll, column scroll, and column height is set to "Fit contents" as it should and the screen vertical alignment is set to Top`: https://x.thunkable.com/copy/71c453c4aae02ee75f2cd8313b46cfca
I do not see the blank space though. Any other settings I might be missing? I placed a button and an image just to have something in the column, but I guess unless you have a lot of stuff in the column, the scrolling won't come into place?

**Comment by jaredgib** [comment] 2020-05-05 15:28
I have an example but it's from my main project. so theres a lot of extra crap but you can see the issue pretty much on each screen. Would that be helpful at all @josmas

**Comment by josmas** [comment] 2020-05-05 15:39
@jaredgib and @AmigoDeluxe actually, I believe the trick to trigger the issue is to set for instance the image to a height of 1500 so it forces the scrolling behaviour, then I can see a red (made the background that color) gap. If you can confirm, that would be great!

I believe we are covering that issue with the changes in column, but need to double check. I'll let you know as soon as I do.

**Comment by josmas** [comment] 2020-05-06 23:52
We've released what we believe is a fix for case 3 above (by @AmigoDeluxe). You will need Companion version 185 to see it though.
We'll keep working on status bar issues within the upgrade also mentioned above.

**Comment by balancedkitchen** [comment] 2020-05-10 16:55
There has been no progress in resolving the problem for more than a month. I no longer regret requesting a refund for my PRO account

**Comment by hencehuman** [comment] 2020-05-10 18:48
Will you let us know how that goes? I've had little luck asking with
billing in the past and Mr. Wei has not replied to my emails about how this
issue has affected me and asking for help.

**Comment by balancedkitchen** [comment] 2020-05-11 08:44
Hello josmas , 
because I'm just criticizing, I decided to help a little. This problem (but to a lesser extent) is observed from the moment you make the screens automatically created when using the TopTabNavigator and the BottomTabNavigator. When there are visible and invisible columns and rows, changes occur after opening the screen. As I said here, the problem only occurs in certain cases. Subsequently, the problem becomes bigger by the accumulation of an error in logic, which is duplicated in each newly created screen function. Carefully check how the open TopTabNavigator and BottomTabNavigator  works when you need to perform the function of cloning elements that need to be loaded. Each time you open the screen, making the original source invisible after cloning. Make a correction in a cloned item (such as text) and refresh the screen for the correction to appear. Opening, not starting! If you find out what caused this problem, you will find a solution for the following ones.
PS: I don't know if I was able to express myself correctly. I am willing to provide the necessary assistance because this platform has great potential. What is extremely annoying is that after each addition of a feature or component I have to check if the old ones are working properly.

**Comment by josmas** [comment] 2020-05-12 13:10
Hi @balancedkitchen thanks for the extra information.
I am not sure I am reading it correctly. I have create this project to try and reproduce the issues you are seeing with columns. In the first tab of the navigator I clone a column, give it a random background color and show it. As you can see, columns keep being added but their size does not change. Second tab does the same cloning but the columns are made invisible, and the original column keeps its size too. Can you let me know if I got that correct or is there some interaction that I am missing that would show the issues with sizes? This is the project https://x.thunkable.com/copy/add0fbb7010a9c1cf05c31dd517c30ab

**Comment by balancedkitchen** [comment] 2020-05-13 09:52
Hello @josmas ,
That’s not exactly what I meant but you seem to have understood me to a certain extent. When looking at the project when opening (Clones Show) а column has to be cloned (Column1). After color change with (Button1)  only the column with change color has to be visible but in your project a second one appears. When going to (Clones hide) and you come back to (Clones Show)  the process has to start again (with one visible column) but we get as many cloned columns as times we have switched between the screens. When using (Button1) the change of colors has to be with every click but it only work once. This issue is not connected with the saving of space for invisible columns or rows, it’s connected with the function for opening the screen.
Sorry it’s really hard for me to explain it to you.

**Comment by josmas** [comment] 2020-05-13 10:29
Hi @balancedkitchen if this is about `Screen.Opens` I would suggest reading the discussion in [here](https://github.com/thunkable/thunkable-issues/issues/476#issuecomment-617171820). There is also a follow up [here](https://github.com/thunkable/thunkable-issues/issues/430) (also linked from that first thread). The code that goes inside `Opens` or `Starts` should not have an effect if run multiple times. This is called _idempotence_ and I realise these are kind of advanced programming concepts, but they become necessary at certain stages when you are developing a more advanced app. We'd be happy to explore some other ways to write the code you use in `Opens`; it's not always possible to find just a replacement or full match, but at times it can be clse. Feel free to open a thread in the [community](https://community.thunkable.com/) and tag me if you want to explore some options.

**Comment by balancedkitchen** [comment] 2020-05-14 06:39
Hello
Take a look at this project (which completely copies your with slight modifications). You will notice that the screen open command does not work the same when the screen is in TopTap Navigator and outside it.

Here is the link: https://x.thunkable.com/copy/9bccee66fc6e3c2a9e7006e6921ed058

**Comment by josmas** [comment] 2020-05-18 13:12
If I am reading this correctly, the different behaviour is due to the fact that a top or bottom navigator can be thought out as subscreens of the navigator itself, that will be alive for as long as the navigator is.

When you open a screen and then navigate out of it, the screen will be `closed`. So in your example, the columns do not accumulate (like in the top navigator) because they are disposed of when the user goes to another screen. When the user goes back, both `Starts` and `Opens` are called.

In the case of the navigator, the navigator screens are not `killed` or disposed of, so by going to another tab in the navigator, the previous one is not `closed` as such. So the columns previously created are still `alive` and they stack.

Does that make any sense?

**Comment by balancedkitchen** [comment] 2020-05-21 07:57
Hello @josmas 
after this detailed explanation, I clarified many of the problems with applications created before this extra. Does that make any sense? I do not know! There are pros and cons. But let us return to the main problem we are discussing here. Here is a link to a really simple application that visualizes the cases in which it appears.

https://x.thunkable.com/copy/a806d6ab7895dd3af9e0b7caa873377b

**Comment by balancedkitchen** [comment] 2020-05-24 13:52
Any progress?

**Comment by AmigoDeluxe** [comment] 2020-05-24 15:09
Heya. I just noticed the below blocks are now available... Perhaps it is worth playing with them to see if they help at all:

![image](https://user-images.githubusercontent.com/7762893/82757536-b2bea200-9de9-11ea-894c-eb42dc63b377.png)

**Comment by balancedkitchen** [comment] 2020-05-24 18:47
@AmigoDeluxe a look at this app and you will understand the big problem.
https://x.thunkable.com/copy/a806d6ab7895dd3af9e0b7caa873377b

**Comment by AmigoDeluxe** [comment] 2020-05-24 18:50
I believe you, I had issues too (I opened the bug report actually 😁) but found a workaround which I posted above. Not ideal but at least it works. I hope you have time to check if the new features I mention in my reply to you.

**Comment by josmas** [comment] 2020-05-25 00:19
@balancedkitchen is the issue that when you make it scrollable the height changes?

A scrollable component cannot have a height of `fill container` because the container is scrollable so it does not have an end as such. So it will reset to fit contents. Not sure if that is what is happening here. If you change the screen background color to anything not white you'll see it when you click on the button at the bottom of your screen.

@AmigoDeluxe we've added those 3 new properties while we are working on the v37 upgrade; hopefully that will provide enough flexibility for now.

**Comment by balancedkitchen** [comment] 2020-05-25 07:16
Okay @josmas. I'm sure you're aware of what bug I'm trying to present to you, even though I haven't followed the basic rule for fill container and fit contents. Here is the same example, but the rule for fill container and fit contents has already been observed. Strange! The application functions in the same way.
Application function:
Visualization of the current state of the columns.
Actions:
1. Launch the application:
Row 1 with contents 2 buttons changing the functions of the columns to scroll or not to scroll
Column 1 - visible and scrolling. Contents Label 1 and Button 3
Column 2 - invisible and scroll
Label 1 - cloned 20 times in Column 1 containing the tex status of all columns.
Label 2 - cloned 20 times in Column 2 containing the tex status of all columns.
Result: BUG
Column 1 does not fill the entire screen (I think this is incorrect)
2. Using Button 2, change Column 2 so that it does not scroll.
Result: Column 1 already fills the entire screen!
3. Using Button 2, change Column 2 to scroll.
Result: Column 1 again does not fill the entire screen!
4. Using Button 4, change Column 2 to be visible and Column 1 to invisible.
Result: BUG
Column 2 does not fill the entire screen (I think this is incorrect)
5. Using Button 1, change Column 1 so that it does not scroll.
Result: Column 2 already fills the entire screen!
I hope that is enough.
PS: I know how to easily get around this bug. But I do not think it is right to leave this problem unresolved. My English is not very good for which I apologize!

https://x.thunkable.com/copy/7efc41466dfd9f0792f2fec3d3f76087

**Comment by josmas** [comment] 2020-05-25 11:30
Hi @balancedkitchen I can now see the interaction between the two columns. If Column 2 is scrollable, it will use up the space even if it is set as hidden. That does not seem right. I did not understand the problem before. I will have a look at it when I have a chance, thanks for the example project that is very helpful.
It seems to be related to the issues we are having with screen orientation on Android, in which scrollable components are also messed up. Thanks!

**Comment by jaredgibb** [comment] 2020-10-05 22:51
@josmas @AmigoDeluxe so after reading this thread. I’m still unsure how to get rid of 
![B9D553C0-2ADC-485A-B3BE-190CD587D870](https://user-images.githubusercontent.com/70493366/95139961-b1a86480-073b-11eb-9ef6-fa1a544cc9e1.jpeg)

**Comment by josmas** [comment] 2020-10-06 07:14
hi @jaredgibb I am not sure what you are pointing at, is there a space between the navigator end and the screen end?
Is this a particular version of iOS? There seem to be a couple of issues with navigator spacing that are new and unrelated to the discussion on this thread. One is that the top navs appear under the status bar, and this seems to be at the bottom, but could also be because that space at the top is not properly handled. Can you please open a different thread and add more details about your layout and what you are testing on? Thanks.

**Comment by MrMazzone** [comment] 2020-10-06 09:34
@josmas @jaredgibb I know a new thread needs to be opened for this. But, I believe that space needs to be there because of the iOS gesture navigation.  I am assuming that this probably only appears when you use the Bottom Nav, as without the spacing think about how difficult it would be to differentiate between nav bar swipe/press and "Charts" button swipe/press.
 
Now, changing the color of that area is a different story...  I believe that padding exists on all versions of iOS with gesture nav, but the background color extends through that area.  Maybe just a tweak to Bottom Nav where the background color is extended past the navigator would easily solve this issue.

**Comment by AmigoDeluxe** [comment] 2020-10-06 14:07
How about setting the screen color to the same blue color as the rest of the screen? Would that change the background color behind the gesture nav bar?

**Comment by jane-d-alt** [comment] 2021-05-18 11:02
In response to the original issue: apps tested an downloaded to Android no longer have any gap at the bottom of the screen. This applies to apps with colorful Screen background colors, apps with components such as Buttons at the bottom of the Screen, and apps with Bottom Tab Navigators. We will close this issue now. Apologies for not following up when this behavior was originally resolved.

**Closed by jane-d-alt** 2021-05-18 11:02 UTC
Labels: bug, follow up, moved
